### ISSUE TITLE
Duplication of order when DMS dissabled

### ISSUE THREAD

**Issue by JacobPlaster** [bitfinexcom/bfx-hf-ui#122]
When the dead man switch is disabled but an order is open. Restarting the application causes for the atomic orders to be duplicated.

Steps to reproduce:
- Create iceberg order
- Disabled deadman switch via settings
- Restart application

Expected:
- only Iceberg order remains open/active (1 atomic order total)

Actual:
- Iceberg order remains open/active
- Iceberg atomic limit order is duplicated and left open (2 atomic orders total)

**Comment by f3rno** [comment]
@JacobPlaster this can be closed now as `bfx-hf-algo` explicitly cancels known orders on startup
