### ISSUE TITLE
npm ERR! errno ENOENT

### ISSUE THREAD

**Issue by poltronSuperstar** [bitfinexcom/bfx-hf-ui#123]
Hi there !
I know this bug has been reported already, but since it's more than one month old, I'll be that annoying guy that opens a duplicate issue :p 
(To seek forgiveness, I'm trying to fix the issue and open a PR if I manage to).

```
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! bfx-hf-ui@3.0.4 start-server: `"npm run start-api-server"`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the bfx-hf-ui@3.0.4 start-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I could give you details but I've not been able to run on three distinct linux distros, with three node versions on each. 
My guess would be a messed dependency. I'll investigate and post a PR if I find

**Comment by f3rno** [comment]
@poltronSuperstar did you manage to find anything?

**Comment by olexiyb** [comment]
I have a similar issue, I had to create manually empty folder ` mkdir ~/.hfdb/`

**Comment by HASHtechvishal** [comment]
apples-Air:react apple$ npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/apple/Desktop/react/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/apple/Desktop/react/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/apple/.npm/_logs/2020-05-07T12_02_10_239Z-debug.log
apples-Air:react apple$ 



how to fix it ``

**Comment by ivanori1** [comment]
@olexiyb  and @HASHtechvishal  do you have this issue ?
