### ISSUE TITLE
Error import OCOCO from bfx-hf-algo

### ISSUE THREAD

**Issue by FiveBoroughs** [bitfinexcom/bfx-hf-ui#129]
Error upon loading the `OrderForm` Component
![image](https://user-images.githubusercontent.com/40718516/79369907-3fe81e80-7f41-11ea-9ed3-3b167e3de1bc.png)

The cause seems to be the `OCOCO` import from `bfx-hf-ago`
Once removed from imports and the list in `getAOs`, the program can load again

**Comment by JacobPlaster** [comment]
Thanks again @FiveBoroughs, is this a clean install of node_modules? It seems like you have an out of date version of bfx-hf-algo

**Comment by FiveBoroughs** [comment]
No this was using a January clone, that `git reset --hard`, `git pull` and `npm install`ed again

Making an new clone fixes this issue and https://github.com/bitfinexcom/bfx-hf-ui/issues/130
