### ISSUE TITLE
Unknown Chart type

### ISSUE THREAD

**Issue by FiveBoroughs** [bitfinexcom/bfx-hf-ui#130]
Upon first loading the App, the chart is absent and a `Unkown Chart Type` message is present
![image](https://user-images.githubusercontent.com/40718516/79371124-614a0a00-7f43-11ea-84d2-39b81df29e02.png)

Changing the Chart type in the settings has no effect
But I think that's a separate issue with the settings, because the field is back to empty when I switch tabs

**Comment by JacobPlaster** [comment]
Thanks @FiveBoroughs, is this just a clean build from master? DO you have any steps to reproduce?

@AntonNazarenko could you check this out please?
