### ISSUE TITLE
UI: Market pulldown 

### ISSUE THREAD

**Issue by spakcjl** [bitfinexcom/bfx-hf-ui#131]
Hi, Just trying out Dist v3.0.5 on mojave OS, both downloaded and locally compiled.
Seeing a problem with the market selection pulldown, on all tabs - Trading terminal, market data etc. Specifically, no ability to scroll down beyond AIO/USD. Any suggestions welcome!

**Comment by ivanori1** [comment]
Hello @spakcjl  this issue should be fixed. any feedback?
