### ISSUE TITLE
Doing some actions on the UI makes it blank.

### ISSUE THREAD

**Issue by tenninebt** [bitfinexcom/bfx-hf-ui#135]
When on the Strategy UI, changing the candle timespan randomly breaks the UI, no error message is shown, just the UI becomes blank. I have noticed some other actions having the same effect.
I don't think the logs are enabled for the UI, but you tell me where I can find them if I'm wrong. How to enable them?

**Comment by ivanori1** [comment]
Hello @tenninebt  is this issue still relevant for you?

**Comment by tenninebt** [comment]
Hey, did not test recently, you can close it up for now.
