### ISSUE TITLE
npm ERR! code ELIFECYCLE on windows

### ISSUE THREAD

**Issue by d1gitalflow** [bitfinexcom/bfx-hf-ui#137]
`Wrote 51 CSS files to C:\Users\tmjj1\Documents\bfx-hf-ui\src\
Creating an optimized production build...
Failed to compile.

./src/redux/reducers/ui/default_layout_market_data.js
  Line 1:17:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 2:16:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 3:20:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 4:13:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 5:91:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 6:7:     Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 7:97:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 8:7:     Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 9:99:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 10:7:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 11:92:   Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 12:7:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 13:100:  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 14:6:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  Line 15:2:    Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

Search for the keywords to learn more about each error.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bfx-hf-ui@3.0.5 build: `cross-env npm run build-css &&  cross-env REACT_APP_TV_URL=http://localhost:9999 REACT_APP_WSS_URL=ws://localhost:45000 node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bfx-hf-ui@3.0.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tmjj1\AppData\Roaming\npm-cache\_logs\2020-05-02T02_29_33_224Z-debug.log
PS C:\Users\tmjj1\Documents\bfx-hf-ui>`

**Comment by Dunc80** [comment]
I got the same error on Ubuntu

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start-server' ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prestart-server', 'start-server', 'poststart-server' ]
5 info lifecycle bfx-hf-ui@3.0.5~prestart-server: bfx-hf-ui@3.0.5
6 info lifecycle bfx-hf-ui@3.0.5~start-server: bfx-hf-ui@3.0.5
7 verbose lifecycle bfx-hf-ui@3.0.5~start-server: unsafe-perm in lifecycle true
8 verbose lifecycle bfx-hf-ui@3.0.5~start-server: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/duncan/honey/bfx-hf-ui/node_modules/.bin:/home/duncan/bin:/home/duncan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle bfx-hf-ui@3.0.5~start-server: CWD: /home/duncan/honey/bfx-hf-ui
10 silly lifecycle bfx-hf-ui@3.0.5~start-server: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env concurrently --kill-others "npm run start-api-server"'
10 silly lifecycle ]
11 silly lifecycle bfx-hf-ui@3.0.5~start-server: Returned: code: 1  signal: null
12 info lifecycle bfx-hf-ui@3.0.5~start-server: Failed to exec start-server script
13 verbose stack Error: bfx-hf-ui@3.0.5 start-server: `cross-env concurrently --kill-others "npm run start-api-server"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid bfx-hf-ui@3.0.5
15 verbose cwd /home/duncan/honey/bfx-hf-ui
16 verbose Linux 4.15.0-99-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-server"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error bfx-hf-ui@3.0.5 start-server: `cross-env concurrently --kill-others "npm run start-api-server"`
22 error Exit status 1
23 error Failed at the bfx-hf-ui@3.0.5 start-server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by Dunc80** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start-server' ]
2 info using npm@6.13.4
3 info using node@v12.16.1
4 verbose run-script [ 'prestart-server', 'start-server', 'poststart-server' ]
5 info lifecycle bfx-hf-ui@3.0.5~prestart-server: bfx-hf-ui@3.0.5
6 info lifecycle bfx-hf-ui@3.0.5~start-server: bfx-hf-ui@3.0.5
7 verbose lifecycle bfx-hf-ui@3.0.5~start-server: unsafe-perm in lifecycle true
8 verbose lifecycle bfx-hf-ui@3.0.5~start-server: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/duncan/honey/bfx-hf-ui/node_modules/.bin:/home/duncan/bin:/home/duncan/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle bfx-hf-ui@3.0.5~start-server: CWD: /home/duncan/honey/bfx-hf-ui
10 silly lifecycle bfx-hf-ui@3.0.5~start-server: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env concurrently --kill-others "npm run start-api-server"'
10 silly lifecycle ]
11 silly lifecycle bfx-hf-ui@3.0.5~start-server: Returned: code: 1  signal: null
12 info lifecycle bfx-hf-ui@3.0.5~start-server: Failed to exec start-server script
13 verbose stack Error: bfx-hf-ui@3.0.5 start-server: `cross-env concurrently --kill-others "npm run start-api-server"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid bfx-hf-ui@3.0.5
15 verbose cwd /home/duncan/honey/bfx-hf-ui
16 verbose Linux 4.15.0-99-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-server"
18 verbose node v12.16.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error bfx-hf-ui@3.0.5 start-server: `cross-env concurrently --kill-others "npm run start-api-server"`
22 error Exit status 1
23 error Failed at the bfx-hf-ui@3.0.5 start-server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by robertkowalski** [comment]
this just seem to be an issue on windows: https://eslint.org/docs/rules/linebreak-style

**Comment by robertkowalski** [comment]
https://github.com/bitfinexcom/bfx-hf-ui/pull/251

**Comment by robertkowalski** [comment]
@d1gitalflow can you check if https://github.com/bitfinexcom/bfx-hf-ui/pull/251 fixes the issue locally for you?

**Comment by Henrique-Arau** [comment]
como faço para corrigir esse erro
