### ISSUE TITLE
TWAP Order

### ISSUE THREAD

**Issue by drazenbencevic** [bitfinexcom/bfx-hf-ui#141]
TWAP order does not work well. When you specify a custom price and set the time interval and put the time of cancellation, when the price drops below the set price, nothing happens. orders do not appear.

**Comment by f3rno** [comment]
Do they not appear after the interval is respected, or do you mean immediately? Can you post your log output (under the `Diagnostics` menu entry)?

**Comment by drazenbencevic** [comment]
Orders do not appear at all. They do not appear immediately or after the
cross. Log Output is empty, 0 kb, so I can't add it as an attachment.

**Comment by drazenbencevic** [comment]
Dražen Benčević
Petra Zoranića 5
32100 Vinkovci
Mob: 098/907-8013

**Comment by ivanori1** [comment]
@drazenbencevic  TWAP are improved, can you double check ?
