### ISSUE TITLE
MA Crossover strategy

### ISSUE THREAD

**Issue by drazenbencevic** [bitfinexcom/bfx-hf-ui#142]
Ma crossover strategy does not work. I mean when a cross occurs two default ema order does not appear and not execute

**Comment by f3rno** [comment]
The UI currently does not support strategy execution, how are you running it?

**Comment by drazenbencevic** [comment]
i am currently trying to run it via UI.

**Comment by f3rno** [comment]
The UI will have strategy execution support in a release this month, for now there is no mechanism/interface for it. Were you using the backtesting UI? If so, can you confirm the backtest shows expected behavior?

**Comment by drazenbencevic** [comment]
I am doing back testing in tradingview, it would be great if you would soon
implement order execution and strategies through UI. If you want I can
offer to test the early versions and report to you if there is any bug.
Also see my TWAP order comment.

**Comment by thefattestcat** [comment]
Any update on this? The MA crossover strategy isn't working via the UI.

**Comment by ivanori1** [comment]
@thefattestcat  It is focus for this release,
