### ISSUE TITLE
Default setting is to enable DMS

### ISSUE THREAD

**Issue by jcbit** [bitfinexcom/bfx-hf-ui#151]
There is a huge warning about enabling DMS yet by default it is enabled. I suggest it be disabled by Default, it already killed my open orders and seems by the warning the HF doesn't want it active as well.

**Comment by JacobPlaster** [comment]
Hi jcbit, good suggestion. We can include that in the next big release.

**Comment by JacobPlaster** [comment]
@AntonNazarenko
