### ISSUE TITLE
Feature Request: Enable favourite trading pairs.

### ISSUE THREAD

**Issue by jcbit** [bitfinexcom/bfx-hf-ui#153]
It is hard to switch between trading pairs. Would be nice if there was a favourites section when one could click on saved trading pairs or a display like Bitfinex's where you can see them sorted by volume or something. That would also be a nice addition, sorting them by other criteria that is not alphabetical.

**Comment by JacobPlaster** [comment]
Another great idea, thanks @jcbit ! Adding for next release.

**Comment by robertkowalski** [comment]
https://github.com/bitfinexcom/bfx-hf-server/pull/61
https://github.com/bitfinexcom/bfx-hf-models/pull/17
