### ISSUE TITLE
Feature Request: Allow to edit open orders

### ISSUE THREAD

**Issue by jcbit** [bitfinexcom/bfx-hf-ui#154]
It would be an awesome feature if you could open active opened orders. By default one things of the HF orders like PingPong etc being able to edit their parameters and update the orders out there. But also, think about for example a scaled order. Would be very neat if I could edit it so that I can move the lower/upper price, etc.

**Comment by JacobPlaster** [comment]
Great idea @jcbit - scoping this for next major release
