### ISSUE TITLE
Ping Pong UI missing fields

### ISSUE THREAD

**Issue by cosmin33** [bitfinexcom/bfx-hf-ui#171]
The Ping/Pong algo order is missing the price fields for buy / sell. The present fields are: amount, order count, submit_delay and cancel_delay.
If I submit the algo order with these fields completed it issues an algo order with the prices set to zero.

**Comment by JacobPlaster** [comment]
Hey @cosmin33, thanks for raising this issue. I've added the bug label and we will take a look into this.

**Comment by JacobPlaster** [comment]
I think I've found the issue. When testing this bug, I noticed that If I change the 'ORDER COUNT' to 2, the fields appear.

Will have a fix out for this in the next release, hopefully Tuesday.
