### ISSUE TITLE
How to install on ubuntu 20.04?

### ISSUE THREAD

**Issue by KoenBal** [bitfinexcom/bfx-hf-ui#176]
Hello,

I assume I have to execute "bfx-hf-ui" in the linux-unpacked folder?
I turned on the flag allow executing file as program.
Can't get it to work, nothing much happens.
Any ideas?

Thx for your assistance

**Comment by ivanori1** [comment]
Sorry for late answer @KoenBal .. did you manage to use HF on ubuntu ?

**Comment by StocknerT** [comment]
I have the same issue:
Not sure what to do with the unpacked-linux folder. How am I supposed to start/install the application from there?

If I build it by myself and try to start the server with `npm run start-server`, I run into following error:

```
> bfx-hf-ui@3.4.0 start-server /home/fuji/bfx-hf-ui
> cross-env concurrently --kill-others "npm run start-api-server"

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn concurrently ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn concurrently',
  path: 'concurrently',
  spawnargs: [ '--kill-others', 'npm run start-api-server' ]
}
```

And npm logs that:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start-server' ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose run-script [ 'prestart-server', 'start-server', 'poststart-server' ]
5 info lifecycle bfx-hf-ui@3.4.0~prestart-server: bfx-hf-ui@3.4.0
6 info lifecycle bfx-hf-ui@3.4.0~start-server: bfx-hf-ui@3.4.0
7 verbose lifecycle bfx-hf-ui@3.4.0~start-server: unsafe-perm in lifecycle true
8 verbose lifecycle bfx-hf-ui@3.4.0~start-server: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/fuji/bfx-hf-ui/node_modules/.bin:/home/fuji/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle bfx-hf-ui@3.4.0~start-server: CWD: /home/fuji/bfx-hf-ui
10 silly lifecycle bfx-hf-ui@3.4.0~start-server: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env concurrently --kill-others "npm run start-api-server"'
10 silly lifecycle ]
11 silly lifecycle bfx-hf-ui@3.4.0~start-server: Returned: code: 1  signal: null
12 info lifecycle bfx-hf-ui@3.4.0~start-server: Failed to exec start-server script
13 verbose stack Error: bfx-hf-ui@3.4.0 start-server: `cross-env concurrently --kill-others "npm run start-api-server"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid bfx-hf-ui@3.4.0
15 verbose cwd /home/fuji/bfx-hf-ui
16 verbose Linux 5.4.0-59-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-server"
18 verbose node v12.18.2
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error bfx-hf-ui@3.4.0 start-server: `cross-env concurrently --kill-others "npm run start-api-server"`
22 error Exit status 1
23 error Failed at the bfx-hf-ui@3.4.0 start-server script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

May someone else experienced that issue already?

**Comment by Daniel1984** [comment]
Hi @StocknerT . When you download the latest release from [here](https://github.com/bitfinexcom/bfx-hf-ui/releases):
1. unzip the content
2. navigate into source folder `cd /dist/linux-unpacked`
3. run the app `./bfx-hf-ui`

Hope this helps.

**Comment by avsek477** [comment]
> I have the same issue:
> Not sure what to do with the unpacked-linux folder. How am I supposed to start/install the application from there?
> 
> If I build it by myself and try to start the server with `npm run start-server`, I run into following error:
> 
> ```
> > bfx-hf-ui@3.4.0 start-server /home/fuji/bfx-hf-ui
> > cross-env concurrently --kill-others "npm run start-api-server"
> 
> events.js:292
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn concurrently ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> Emitted 'error' event on ChildProcess instance at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
>     at onErrorNT (internal/child_process.js:469:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   errno: 'ENOENT',
>   code: 'ENOENT',
>   syscall: 'spawn concurrently',
>   path: 'concurrently',
>   spawnargs: [ '--kill-others', 'npm run start-api-server' ]
> }
> ```
> 
> And npm logs that:
> 
> ```
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start-server' ]
> 2 info using npm@6.14.5
> 3 info using node@v12.18.2
> 4 verbose run-script [ 'prestart-server', 'start-server', 'poststart-server' ]
> 5 info lifecycle bfx-hf-ui@3.4.0~prestart-server: bfx-hf-ui@3.4.0
> 6 info lifecycle bfx-hf-ui@3.4.0~start-server: bfx-hf-ui@3.4.0
> 7 verbose lifecycle bfx-hf-ui@3.4.0~start-server: unsafe-perm in lifecycle true
> 8 verbose lifecycle bfx-hf-ui@3.4.0~start-server: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/fuji/bfx-hf-ui/node_modules/.bin:/home/fuji/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> 9 verbose lifecycle bfx-hf-ui@3.4.0~start-server: CWD: /home/fuji/bfx-hf-ui
> 10 silly lifecycle bfx-hf-ui@3.4.0~start-server: Args: [
> 10 silly lifecycle   '-c',
> 10 silly lifecycle   'cross-env concurrently --kill-others "npm run start-api-server"'
> 10 silly lifecycle ]
> 11 silly lifecycle bfx-hf-ui@3.4.0~start-server: Returned: code: 1  signal: null
> 12 info lifecycle bfx-hf-ui@3.4.0~start-server: Failed to exec start-server script
> 13 verbose stack Error: bfx-hf-ui@3.4.0 start-server: `cross-env concurrently --kill-others "npm run start-api-server"`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:315:20)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:315:20)
> 13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> 14 verbose pkgid bfx-hf-ui@3.4.0
> 15 verbose cwd /home/fuji/bfx-hf-ui
> 16 verbose Linux 5.4.0-59-generic
> 17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-server"
> 18 verbose node v12.18.2
> 19 verbose npm  v6.14.5
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error bfx-hf-ui@3.4.0 start-server: `cross-env concurrently --kill-others "npm run start-api-server"`
> 22 error Exit status 1
> 23 error Failed at the bfx-hf-ui@3.4.0 start-server script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
> ```
> 
> May someone else experienced that issue already?

please run this command: npm i concurrently
it should work then

**Comment by StocknerT** [comment]
Thx, got it with the unpacked version.

**Comment by ivanori1** [comment]
closed
