### ISSUE TITLE
Having an issue with showing margin balance on account tab.

### ISSUE THREAD

**Issue by waynetwleung** [bitfinexcom/bfx-hf-ui#230]
One of my laptops are able to see the margin balance in my account fine whilst the other laptop wouldn't. I tried to delete the entire honey framework folder and copied a fresh version of the app, however it still wouldn't show. Also tried using a fresh copy of the app in a new windows login, same result. I wonder if there are some files that had been written but I have missed when trying to delete for the fresh install?

**Comment by ivanori1** [comment]
Hello @waynetwleung  and thanks for writing down your issue: Tell me do you use the same API keys for both of your laptops and a) do you not see balance at all, b) do not see all margin balances c) do not see just some specific margin wallet balance?

**Comment by robertkowalski** [comment]
abandoned issue, closing.
