### ISSUE TITLE
The UI lost connection somehow within 2 hours !

### ISSUE THREAD

**Issue by shingtat2** [bitfinexcom/bfx-hf-ui#247]
The UI lost connection somehow within 2 hours !
The connection indicators at the bottom right are still green.
But the algorithms and orders are Offline.
Also, it's unable to send new Algorithms again, no response after clicking submitted.
The algorithm I use is default PingPong , unable to work since it keeps shutting down.

**Comment by ivanori1** [comment]
Hello @shingtat2  thanks for your effort to write down your issue, I see that you created github today also. so you had double work.

**Comment by robertkowalski** [comment]
@shingtat2 any updates on this?

**Comment by shingtat2** [comment]
Yes, I registered just to leave a comment.
What do you want me to update? have you found the issue?

**Comment by robertkowalski** [comment]
@shingtat2 we need more information on this issue in order to help you. 

1. has your PC been in sleep mode and you lost connection when the issue happens?

2. do you get any errors when trying to summit? (check bell icon for all notifications)
