### ISSUE TITLE
is not recognized as an internal or external command

### ISSUE THREAD

**Issue by soft2fire** [bitfinexcom/bfx-hf-ui#249]
hi
i have problem in strat project
'REACT_APP_TV_URL' is not recognized as an internal or external command,
operable program or batch file.

 "start": "REACT_APP_DEV=1 REACT_APP_TV_URL=http://localhost:9999 REACT_APP_WSS_URL=ws://localhost:45000 node scripts/start.js",
    "build": "npm run build-css && REACT_APP_TV_URL=http://localhost:9999 REACT_APP_WSS_URL=ws://localhost:45000 node scripts/build.js",

**Comment by robertkowalski** [comment]
hmm... probably you are on windows?

for windows you will need something like git-shell.

`REACT_APP_TV_URL` is not a command, it is an environment variable set.
