### ISSUE TITLE
Sudenly Stopped Algo order on 3.4.0 Honey 

### ISSUE THREAD

**Issue by ljrossi** [bitfinexcom/bfx-hf-ui#279]
The ALGO I run suddenly stops randomly after 10 or 30 minutes.
In some cases I did have a disconect error before de algo stop notification.
I test both LINUX and WINDOWS versions on windows 10 and in ubuntu 20.04 in diferent locations . not sure if is a problem with slow internet ....but any ways it should not just shut down the algo, it might resume from where it was...at least if the bandwith has some shortage or small interrupts.
Not sure wich is the problem.....

**Comment by xf3rno** [comment]
@JacobPlaster logs would be useful here, this PR fixes the app menu entry: https://github.com/bitfinexcom/bfx-hf-ui/pull/281
