### ISSUE TITLE
I.SAR is not a constructor

### ISSUE THREAD

**Issue by r3l0c** [bitfinexcom/bfx-hf-ui#290]
Error `I.SAR is not a constructor`

`(I) => {
  const indicators = {
  	emaL: new I.EMA([100, 'high']),
  	emaS: new I.EMA([10, 'low']),
    SAR: new I.SAR([0.08,0.04,0.002])
  }
  
  indicators.emaL.color = '#00ff00'
  indicators.emaS.color = '#ff0000'
  indicators.SAR.color = '#ffffff'
    
  return indicators
}`

**Comment by xf3rno** [comment]
@r3l0c there is no `SAR` indicator in `bfx-hf-indicators`; what do you expect `SAR` to be here?
