### ISSUE TITLE
bfx-report integration

### ISSUE THREAD

**Issue by ph4z** [bitfinexcom/bfx-hf-ui#314]
Hello,

Do you plan to integrate the bfx-report-ui into the honey framework ? 
Both are amazing tools, and having a "report" page into the hf-ui would be perfect.

Regards.

**Comment by ivanori1** [comment]
Hello @ph4z , not for now. It is not included into our 2021 roadmap,  but you gave great idea.

**Comment by ph4z** [comment]
Hi @ivanori1 I will probably have a look on it in the coming weeks.

**Comment by ivanori1** [comment]
not in the priority list.. sorry
