### ISSUE TITLE
Support for additional features

### ISSUE THREAD

**Issue by ph4z** [bitfinexcom/bfx-hf-ui#318]
Hi,

I would be very happy to see the below features implemented (in order of preference)

**1. wallet transfer**: each time I have to switch to the bfx website when a wallet transfer is needed.
**2. funding:** actually I can only run strategies for spot or margin markets
**3. withdraw:** same as wallet transfer

Is there any plan for implementing these features ?

**Comment by ph4z** [comment]
I forget to mention **subacounts**.
Actually you can only run a strategy for a single account because you need to overwrite API credentials each time you want to switch to a diffrent subaccount.

**Comment by ivanori1** [comment]
the main accent for now is on Algo orders and executing strategies, because copy-cat of web-app would not make too much seance..
