### ISSUE TITLE
santiment integration

### ISSUE THREAD

**Issue by ph4z** [bitfinexcom/bfx-hf-ui#389]
I would like to integrate santiment metrics into HF (I have access to their API).
I don't really enjoy reinventing the wheel, so I was wondering if you plan to release some code of  your brillant implementation at https://santiment.bitfinex.com ?

**Comment by ivanori1** [comment]
well currently not on our radar, be are redesigning HF and implementing https://github.com/bitfinexcom/ufx-ui , but final goal is to make HF looks similar to web-app
