### ISSUE TITLE
API log cluttered : Error canceling / Order not found [Ping-Pong]

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#440]
Hello.

Whenever (9 out of 10) orders get flushed, the log shows unsuccessful attempts to cancel orders that are no longer there. Apart from the log being unreadable, how do I get the cancelling routine to behave?

> [0m 2021-05-29T03:29:26.219Z bfx:hf:algo:bfx-ping_pong:1622253853604 received error while canceling order(id: 66746799076, cid: 1622258780830): LIMIT -0.00022 @ 36719 [ERROR: Notification {
> [0m   _events: [Object: null prototype] {},
> [0m   _eventsCount: 0,
> [0m   _maxListeners: undefined,
> [0m   emptyFill: null,
> [0m   _fields: {
> [0m     mts: 0,
> [0m     type: 1,
> [0m     messageID: 2,
> [0m     notifyInfo: 4,
> [0m     code: 5,
> [0m     status: 6,
> [0m     text: 7
> [0m   },
> [0m   _boolFields: [],
> [0m   mts: 1622258965586,
> [0m   type: 'oc-req',
> [0m   messageID: null,
> [0m   notifyInfo: [
> [0m     66746799076, null, null,
> [0m     null,        null, null,
> [0m     null,        null, null,
> [0m     null,        null, null,
> [0m     null,        null, null,
> [0m     null,        null, null,
> [0m     0,           0,    null,
> [0m     null,        null, 0,
> [0m     0,           null, null,
> [0m     null,        null, null,
> [0m     null,        null
> [0m   ],
> [0m   code: null,
> [0m   status: 'ERROR',
> [0m   text: 'Order not found.',
> [0m   [Symbol(kCapture)]: false
> [0m }]

Thank you kindly, 
miro

**Comment by robertkowalski** [comment]
Hi miro,

thanks for your bug report. We will work on improving the log output by shrinking the size of the cancel order error notifications.

https://github.com/bitfinexcom/bfx-hf-algo/pull/100 will improve the other issue reported and we will land it right after the 3.11 release

**Comment by pointops** [comment]
Robert, thank you for watching over this.

On my builds (3.13.0 now) the situation seems unchanged. A lot of attempts to close non-existing orders and lengthy warnings.

[](https://pastebin.com/raw/9EP2sb34)

Understandably the efforts are better placed on resolving the underlying issue than shortening the message. Is this the same reason the order recovery pop-up shows non-existing algos?

Sorry for mixing up two issues, but perhaps we can close this one as "won't fix".
miro

**Comment by pointops** [comment]
IDK, closing.

**Comment by pointops** [comment]
IDK, closing.

**Comment by avsek477** [comment]
> IDK, closing.

It's fix was merged in v3.16.0 .. Can you check again please @pointops. It should be fixed.

**Comment by pointops** [comment]
Indeed it is.
