### ISSUE TITLE
Algo orders cancelling

### ISSUE THREAD

**Issue by Godin777** [bitfinexcom/bfx-hf-ui#464]
Hey, I don't know if this is a feature or a bug but after sometime my algo orders will cancel seemingly on their own which is annoying. 
`2021-06-07T07:10:24.408Z bfx:hf:algo:ao-host:ws2:bind-bus enqueue open
2021-06-07T07:10:24.408Z bfx:hf:algo:ao-host:ws2:process-message process open
2021-06-07T07:10:24.411Z bfx:hf:server:algo-worker meta reloaded
2021-06-07T07:10:24.683Z bfx:hf:algo:ao-host:ws2:bind-bus enqueue auth:success
2021-06-07T07:10:24.684Z bfx:hf:algo:ao-host:ws2:process-message process auth:success
2021-06-07T07:10:24.871Z bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:snapshot
2021-06-07T07:10:24.871Z bfx:hf:algo:ao-host:ws2:process-message process order:snapshot
2021-06-07T07:27:45.188Z bfx:hf:server:ws-server:api removed selected orders []`

This is what was in the logs before the algo was cancelled. Any solution available to prevent this from happening? Running HF on a server through the WIN app.

**Comment by avsek477** [comment]
> Hey, I don't know if this is a feature or a bug but after sometime my algo orders will cancel seemingly on their own which is annoying.
> `2021-06-07T07:10:24.408Z bfx:hf:algo:ao-host:ws2:bind-bus enqueue open 2021-06-07T07:10:24.408Z bfx:hf:algo:ao-host:ws2:process-message process open 2021-06-07T07:10:24.411Z bfx:hf:server:algo-worker meta reloaded 2021-06-07T07:10:24.683Z bfx:hf:algo:ao-host:ws2:bind-bus enqueue auth:success 2021-06-07T07:10:24.684Z bfx:hf:algo:ao-host:ws2:process-message process auth:success 2021-06-07T07:10:24.871Z bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:snapshot 2021-06-07T07:10:24.871Z bfx:hf:algo:ao-host:ws2:process-message process order:snapshot 2021-06-07T07:27:45.188Z bfx:hf:server:ws-server:api removed selected orders []`
> 
> This is what was in the logs before the algo was cancelled. Any solution available to prevent this from happening? Running HF on a server through the WIN app.

Hi @Godin777 , you can disable the DMS option in the settings page to prevent this from happening :)

**Comment by sparck69** [comment]
Hi @avsek477, thanks for the reply. DMS was disabled the entire time which is why I am confused, will re-install and try running again.

**Comment by robertkowalski** [comment]
no updates in 20 days, seems to be solved
