### ISSUE TITLE
Chart doesn't exists

### ISSUE THREAD

**Issue by AntonNazarenko** [bitfinexcom/bfx-hf-ui#48]
![image](https://user-images.githubusercontent.com/51406639/68306145-a4a96e00-00b1-11ea-8220-b116ac14d41d.png)
After the first launch chart doesn't exist.

**Comment by f3rno** [comment]
I cannot reproduce this, @AntonNazarenko can you confirm it is still a problem?

**Comment by AntonNazarenko** [comment]
no, fixed it already

**Comment by f3rno** [comment]
@JacobPlaster can you close this?
