### ISSUE TITLE
BFX UI: Dropdown in Order form is clipped horizontally

### ISSUE THREAD

**Issue by Nazeh** [bitfinexcom/bfx-hf-ui#485]
Dropdown in the Order form is wider than its containers that have `overflow: scroll` and `overflow: hidden`. 
This is caused by the `left: 0 - spacing();` and `right: 0 - spacing();` at `.hfui-orderform__wrapper .ufx-dropdown .list`

Current behavior: 
![Before](https://user-images.githubusercontent.com/40009100/121772868-e7ca9d80-cb80-11eb-927f-94c1ceceb131.png)

Expected behavior: 
![After](https://user-images.githubusercontent.com/40009100/121772934-54459c80-cb81-11eb-8cce-d7c6bf28a03c.png)

**Comment by ivanori1** [comment]
Hello @Nazeh , Thanks for the fix, exchange margin will have different design, but this will be useful for other dropdown in order form
