### ISSUE TITLE
Order book stops receiving data

### ISSUE THREAD

**Issue by JacobPlaster** [bitfinexcom/bfx-hf-ui#51]
This issue was soon in the compiled electron app.

Steps to reproduce:

1. load application
2. Sign in
3. Connect API keys
4. Switch between "Market data" and "Trading terminal" view lots of times

Err:

Orderbook will freeze as if no data is being received from websocket. This might be caused by the websocket which attempts to unsubscribe from the websocket whenever you change page.

**Comment by ivanori1** [comment]
This is fixed, and task can be closed
