### ISSUE TITLE
Error Not responding

### ISSUE THREAD

**Issue by JacobPlaster** [bitfinexcom/bfx-hf-ui#52]
This issue was found in the electron JS application.

Steps to reproduce:

1. Load application
2. Sign in
3. Navigate to "Market data"
4. Interact with chart

Err:

Application freezes with "Not responding" status for a few seconds. This happens multiple times, not sure if there is some blocking code (prehaps chart waiting for data?) or if there is some really inefficient render patterns.

**Comment by JacobPlaster** [comment]
Update on this, I notice the problem also occurs if you pan the chart to a previous time. Maybe it causes a problem when requesting a bunch of previous candles?

**Comment by JacobPlaster** [comment]
^ We should also rely on the data server in order to fetch candles (if we dont already) since that automatically caches candles locally

**Comment by f3rno** [comment]
This can be closed I think, unless you see it again with the new chart.
