### ISSUE TITLE
Favourite pair: filter de-selects

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#547]
The starred-only filter does not get memorized.

![Ticker panel](https://user-images.githubusercontent.com/80652610/125837755-48f7beca-e02a-4b5f-9e08-2c8ebcfd0a11.png)

Navigating away from the Trading Terminal, for instance to the Market Data screen, the selection of filter is lost once coming back. Same after reloading the electron app or relaunching in-browser via page refresh.

Thanks, 
miro

**Comment by ivanori1** [comment]
Fix is it the master branch.. will close this issue after new official release 3.15,
Thanks for noticing

**Comment by pointops** [comment]
Tested yesterday, noticed the icons too. Very neat and pretty.

much appreciated,
miro
