### ISSUE TITLE
Hosting HF on PaaS with Docker

### ISSUE THREAD

**Issue by kingjkz** [bitfinexcom/bfx-hf-ui#569]
Hi there
thanks for the good work.
I'm trying to host the production build on an ubuntu docker, image: 

- FROM node:alpine

Here are the steps I took:

- git clone https://github.com/bitfinexcom/bfx-hf-ui.git
- mkdir -p /usr/src/app && cp -r /bfx-hf-ui/ /usr/src/app
- cd /usr/src/app/bfx-hf-ui
- npm run fetch-core
- 
- /# Injecting "Http-Server" as dependency into "package.json"  of  "bfx-hf-ui"  to serve the ./build 
- sed -i 's_"open": "^7.0.1"_"open": "^7.0.1",\n\t"http-server": "^13.0.0"_g' ./package.json
-
- npm install
- cd /usr/src/app/bfx-hf-ui/bfx-hf-ui-core
-
- /# Chaging the build command in "package.json" of "bfx-hf-ui-core"  so now the build script passes the needed ENVs for a production build NOT as a portable Electron app; BUT as a production build suitable for self-hosting
- -RUN sed -i 's,GENERATE_SOURCEMAP=false cross-env npm run build-css && env-cmd -e production node scripts/build.js,cross-env NODE_ENV=production PUBLIC_URL=https://some.website REACT_APP_WSS_URL=ws://some.website:45000 REACT_APP_DS_URL=ws://some.website:23521 REACT_APP_WS_API_URL=wss://some.website:45000 REACT_APP_IS_ELECTRON_APP=false node --max-old-space-size=4096 scripts/build.js,g' ./package.json
-
- npm run build-css
- npm run build:prod
-
- cd ..
- /## Now that it's cooked, we get ready to serve it ##
- sed -i 's+"release": "electron-builder -p always"+"release": "electron-builder -p always",\n\t"prod": "cross-env PORT=80 http-server ./build"+g' ./package.json
- sed -i 's_x\\"_x\\" \\"npm run prod\\"_g' ./package.json
- npm run postbuild

- mkdir ~/.honeyframework
- touch ~/.honeyframework/algos.json
- touch ~/.honeyframework/hf-bitfinex.json
- touch ~/.honeyframework/ui.json

- npm run start-server

AND BAAM!

> bfx-hf-ui@3.15.0 start-server
> cross-env concurrently --kill-others "npm run start-api-server" "npm run start-ds-bitfinex" "npm run prod"

> [2] 
> [2] > bfx-hf-ui@3.15.0 prod
> [2] > cross-env PORT=80 http-server ./build
> [2] 
> [1] 
> [1] > bfx-hf-ui@3.15.0 start-ds-bitfinex
> [1] > cross-env node scripts/start-ds-bitfinex.js
> [1] 
> [0] 
> [0] > bfx-hf-ui@3.15.0 start-api-server
> [0] > cross-env ALGO_LOG=true ALGO_LOG_DIR=logs node scripts/start-api-server.js
> [0] 
> [2] Starting up http-server, serving ./build
> [2] Available on:
> [2]   http://127.0.0.1:80
> [2]   http://10.0.1.77:80
> [2]   http://172.18.0.4:80
> [2]   http://10.0.0.10:80
> [2] Hit CTRL-C to stop the server
> [2] http-server stopped.
> [0] npm run start-api-server exited with code 1
> --> Sending SIGTERM to other processes..
> [1] npm run start-ds-bitfinex exited with code 1
> --> Sending SIGTERM to other processes..
> [2] npm run prod exited with code SIGTERM
> [0] 2021-08-14T19:10:18.186Z bfx:hf:models:adapter-lowdb loading from /root/.honeyframework/ui.json
> [0] 2021-08-14T19:10:18.211Z bfx:hf:models:adapter-lowdb loading from /root/.honeyframework/algos.json
> [0] 2021-08-14T19:10:18.226Z bfx:hf:server:get-market-data fetching market list
> [0] (node:99) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/src/app/bfx-hf-ui/node_modules/bfx-hf-indicators/package.json' of './dist/index.js'. Please either fix that or report it to the module author
> [0] (Use `node --trace-deprecation ...` to show where the warning was created)
> [0] (node:99) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/src/app/bfx-hf-ui/node_modules/bfx-hf-indicators/package.json' of './dist/index.js'. Please either fix that or report it to the module author
> [0] (node:99) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/src/app/bfx-hf-ui/node_modules/bfx-hf-indicators/package.json' of './dist/index.js'. Please either fix that or report it to the module author
> [0] 2021-08-14T19:10:18.469Z bfx:hf:server:get-market-data fetched 343 markets
> [0] 2021-08-14T19:10:18.479Z bfx:hf:server:ws-server:api starting on port 45000
> [0] 2021-08-14T19:10:18.486Z bfx:hf:server:http-proxy Starting Proxy at 127.0.0.1:45001 for base https://api-pub.bitfinex.com
> [1] 2021-08-14T19:10:19.194Z bfx:hf:models:adapter-lowdb loading from /root/.honeyframework/hf-bitfinex.json
> [1] 2021-08-14T19:10:19.247Z bfx:hf:data-server websocket API open on port 23521
> [1] (node:86) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/src/app/bfx-hf-ui/node_modules/bfx-hf-indicators/package.json' of './dist/index.js'. Please either fix that or report it to the module author
> [1] (Use `node --trace-deprecation ...` to show where the warning was created)
> [1] (node:86) [DEP0128] DeprecationWarning: Invalid 'main' field in '/usr/src/app/bfx-hf-ui/node_modules/bfx-hf-indicators/package.json' of './dist/index.js'. Please either fix that or report it to the module author
> [2] [2021-08-14T19:13:52.736Z]  "GET /icon_font/styles.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0"
> [2] (node:63) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
> [2] (Use `node --trace-deprecation ...` to show where the warning was created)

Forward ports 45000 & 23521 and You might think this cookie is done, but we I run it, even though It seems to be working fine; I get this error in browser's consol indicating something went wrong:

> linkify option is removed. Use linkify plugin instead:
> 
> import Remarkable from 'remarkable';
> import linkify from 'remarkable/linkify';
> new Remarkable().use(linkify)
> 
> 
> index.browser.js:5848:12
> hfui:rx:s:ws-hfui:worker-connection attempting connection to bfx-hf-server... +0ms common.js:112:12
> 
> DOMException: The operation is insecure. io-6de156f3.js:116:10
>     Redux 19
>     1874 StoreWrapper.js:12
>     f (index):1
>     970 main.0ac1aa24.chunk.js:1
>     f (index):1
>     r (index):1
>     t (index):1
>     <anonymous> main.0ac1aa24.chunk.js:1
> The above error occurred in task _a
>     created by ln
>     created by mr
> 
> Tasks cancelled due to error:
> takeEvery(WS_BUFF_SEND, Ta)
> takeEvery(WS_FLUSH_QUEUE, Ta)
> takeEvery(WS_CONNECTED, La)
> takeEvery(WS_RECONNECTED, Ba)
> takeEvery(WS_DISCONNECTED, Ha)
> takeEvery(WS_ADD_CHANNEL_REQ, Ja)
> takeEvery(WS_RM_CHANNEL_REQ, $a)
> takeEvery(WS_UNSUBSCRIBE, Xa)
> takeEvery(WS_SUBSCRIBE, Ya)
> takeEvery(WS_FLUSH_DATA_FROM_EXCHANGE, rn)
> takeEvery(WS_BUFFER_DATA_FROM_EXCHANGE, cn)
> takeEvery(PUB_WS_SUBSCRIBED, sn)
> Ra
> ya
> kn
> Xn
> tr
> sr
> pr
> Qg
> Ko io-6de156f3.js:117:10
> bfx-hf-ui-core v3.14.0 index.js:15:8
> 
> 
> hfui:main local storage DB version 2 +0ms common.js:112:12
> hfui:main boot version 3.14.0 +0ms common.js:112:12
> 

And web app stops loading in browser.

Would you kindly help me get it running?
And one more favore to ask; Is it possible to make it use localhost so I wouldn't need to forward those important ports?
I've tried localhost with no luck.

And is it alright if I remove 

- " || 'wss://api-pub.bitfinex.com/ws/2'" 

from line 20 in :

- "bfx-hf-ui-core/src/redux/config.js" 

So in case the localhost didn't resopond we avoid attempting access to Bitfinex's API directly ?

**Comment by Blaumaus** [comment]
Yes, it is possible to make this run on localhost.
Please, try setting the next variables:
`REACT_APP_WSS_URL` to `ws://localhost:45000`
`REACT_APP_UFX_PUBLIC_API_URL` to `http://localhost:45001`
`REACT_APP_DS_URL` to `ws://localhost:23521`
`REACT_APP_UFX_WSS_URL` to `wss://api-pub.bitfinex.com/ws/2`
also in this case it might be a good idea to set `REACT_APP_IS_ELECTRON_APP` to `true`.

The `bfx-hf-ui-core` will work with these presets locally, and with serve npm package (`serve -s build`) you can run the compiled, production version.

If you want to host it on PaaS, try using something like NGINX websocket proxy for API and DS servers.

**Comment by ivanori1** [comment]
@kingjkz  can we close the task? any other question?
