### ISSUE TITLE
Zombie AOs after remote atomic flush

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#575]
v 3.15.0 manually built on Debian WSL2 on 2021-08-22, cloned directly from here.
running in browser W10/Firefox

Setup: 
2x active Ping/Pong AOs, to sell and buy from Margin with 10 slices each.

Case:
Orders flushed without user intervention, remotely somehow again (BadConnectivity modal did NOT show up)

Behaviour: 
**- BFX Web Terminal**: The individual atomics, as well as their 2 respective groups, are removed, info panel pop-up advises about the cancellation. This is OK. Zero orders indicated as expected.

![obrazek](https://user-images.githubusercontent.com/80652610/130357468-637af179-4b19-481f-aeec-ceb123fba4a4.png)

** bfx-hf-ui**
After a while, the indicated atomics go from 20 to 0 as expected.
However, the 2x AO prescriptions remain: 

![obrazek](https://user-images.githubusercontent.com/80652610/130357598-5878c2dd-9cc7-4d1e-9198-d50ab5fed08a.png)

*logs from* start-server *terminal window*

>   bfx:hf:algo:ao-host triggering orders:order_fill for AO bfx-ping_pong [gid 1629637919259] +0ms
  bfx:hf:algo:bfx-ping_pong:1629637919259 submitting pong order 48818 for ping 48796 +3m
  bfx:hf:algo:bfx-ping_pong:1629637919259 emit exec:order:submit:all [at onOrdersOrderFill (/home/user/bfx-hf-ui/node_modules/bfx-hf-algo/lib/ping_pong/events/orders_order_fill.js:102:9)] +1ms
  bfx:hf:algo:bfx-ping_pong:1629637919259 submitting order LIMIT -0.001 @ 48818 [gid 1629638118598] 1629637919259 +0ms
  bfx:hf:algo:bfx-ping_pong:1629637919259 submitOrder (attempt 1): (cid: 1629638118598) LIMIT order on BTC/USD for -0.00100000 @ 48818 [at /home/user/bfx-hf-ui/node_modules/bfx-hf-algo/lib/host/events/submit_all_orders.js:71:11] +1ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +3ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +0ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +0ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:new +537ms
  bfx:hf:algo:bfx-ping_pong:1629637919259 order successfully submitted: LIMIT -0.001 @ 48818 ACTIVE +538ms
  bfx:hf:algo:bfx-ping_pong:1629637919259 updateState [at onOrdersOrderFill (/home/user/bfx-hf-ui/node_modules/bfx-hf-algo/lib/ping_pong/events/orders_order_fill.js:103:9)] +0ms  bfx:hf:algo:bfx-ping_pong:1629637919259 emit state:update [at updateState (/home/user/bfx-hf-ui/node_modules/bfx-hf-algo/lib/host/gen_helpers.js:424:13)] +0ms
  bfx:hf:algo:ao-host:ws2:process-message process order:close [0/0.001 @ 48792 EXECUTED @ 48792.0(0.001)] +542ms
  bfx:hf:algo:ao-host triggering order event orders:order_close for AO bfx-ping_pong [gid 1629637834764, o cid 1629637916618, 0.001 @ 48792 EXECUTED @ 48792.0(0.001)] +541ms
  bfx:hf:algo:ao-host triggering order event orders:order_fill for AO bfx-ping_pong [gid 1629637834764, o cid 1629637916618, 0.001 @ 48792 EXECUTED @ 48792.0(0.001)] +0ms
  bfx:hf:algo:ao-host triggering orders:order_fill for AO bfx-ping_pong [gid 1629637834764] +0ms
  bfx:hf:algo:ao-host:ws2:bind-bus error processing: TypeError: Cannot read property '1' of undefined
    at extract (/home/user/bfx-hf-ui/node_modules/bfx-hf-algo/lib/ping_pong/util/ping_pong_table.js:14:29)
    at onOrdersOrderFill (/home/user/bfx-hf-ui/node_modules/bfx-hf-algo/lib/ping_pong/events/orders_order_fill.js:47:42)
    at AOHost.triggerAOEvent (/home/user/bfx-hf-ui/node_modules/bfx-hf-algo/lib/ao_host.js:824:11)
    at /home/user/bfx-hf-ui/node_modules/bfx-hf-algo/lib/ao_host.js:766:20
    at Array.map (<anonymous>)
    at AOHost.triggerOrderEvent (/home/user/bfx-hf-ui/node_modules/bfx-hf-algo/lib/ao_host.js:732:33)
    at module.exports (/home/user/bfx-hf-ui/node_modules/bfx-hf-algo/lib/host/ws2/process_message.js:111:15)
    at async processMessages (/home/user/bfx-hf-ui/node_modules/bfx-hf-algo/lib/host/ws2/bind_bus.js:30:7) +3ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +4s
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +1m
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +28s
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +0ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +0ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +1ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +0ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +0ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +0ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +0ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +0ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +1s
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +1ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +0ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +0ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +1ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close +0ms

**Comment by pointops** [comment]
~/.honeyframework/algos.json indeed logs the AOs as active still, which is no longer true.

[algos.json.txt](https://github.com/bitfinexcom/bfx-hf-ui/files/7027491/algos.json.txt)

**Comment by bhoomij** [comment]
https://github.com/bitfinexcom/bfx-hf-algo/pull/183

**Comment by ivanori1** [comment]
merged fix, thanks @pointops  for highlighting..
