### ISSUE TITLE
AO fails to launch, WS problem

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#588]
![obrazek](https://user-images.githubusercontent.com/80652610/132099935-cf91a960-0410-435d-abeb-8e76224af3dd.png)
![obrazek](https://user-images.githubusercontent.com/80652610/132099948-f8e45309-b273-48f6-bb00-97924078519c.png)

This is preceded by an error during the api-server launch, log trace below.
**Unhandled rejection: 500 - ["error",null,"ERR_TOKEN_CAPS_POLICY_INVALID"]**

Build 3.16.0 + latest cloned from Github repository SEP 04 17:00 UTC.
WSL2 Debian / run-in-browser / Edge

Repeated occurrence since about 4 days ago. The original 3.16.0 as released did not have this trouble :-/

**Comment by pointops** [comment]
bfx:hf:models:adapter-lowdb loading from /home/username/.honeyframework/ui.json +0ms
  bfx:hf:models:adapter-lowdb loading from /home/username/.honeyframework/algos.json +10ms
  bfx:hf:server:get-market-data fetching market list +0ms
  bfx:hf:server:get-market-data fetched 350 markets +193ms  bfx:hf:server:ws-server:api starting on port 45000 +0ms
  bfx:hf:server:http-proxy Starting Proxy at 127.0.0.1:45001 for base https://api.bitfinex.com/ +0ms
  bfx:hf:server:ws-server:api client 1630761345094 connected +1m
  bfx:hf:server:ws-server:api identified +374ms
  bfx:hf:server:algo-worker spawning bfx algo host (dms enabled) [aff xZvWHMNR] +0ms
  bfx:hf:server:ws-server:api opening auth bfx connection (dms enabled) +156ms
Unhandled rejection: 500 - ["error",null,"ERR_TOKEN_CAPS_POLICY_INVALID"]
! StatusCodeError -> StatusCodeError (/home/username/bfx-hf-ui/node_modules/request-promise-core/lib/errors.js) [32:%s]! plumbing.callback -> Request (/home/username/bfx-hf-ui/node_modules/request-promise-core/lib/plumbing.js) [104:%s]
! RP$callback -> Request (/home/username/bfx-hf-ui/node_modules/request-promise-core/lib/plumbing.js) [46:%s]
! self.callback -> Request (/home/username/bfx-hf-ui/node_modules/request/request.js) [185:%s]
! emit -> Request (events.js) [400:%s]
! Request.<anonymous> -> Request (/home/username/bfx-hf-ui/node_modules/request/request.js) [1154:%s]
! emit -> Request (events.js) [400:%s]
! IncomingMessage.<anonymous> -> IncomingMessage (/home/username/bfx-hf-ui/node_modules/request/request.js) [1076:%s]
! onceWrapper -> Object (events.js) [519:%s]
! emit -> IncomingMessage (events.js) [412:%s]
! endReadableNT -> null (internal/streams/readable.js) [1317:%s]
! processTicksAndRejections -> process (internal/process/task_queues.js) [82:%s]

source from /home/username/bfx-hf-ui/node_modules/request-promise-core/lib/errors.js:32
    this.error = body; // legacy attribute
    this.options = options;
    this.response = response;

    if (Error.captureStackTrace) { // required for non-V8 environments
!!!
        Error.captureStackTrace(this);
!!!
    }

}
StatusCodeError.prototype = Object.create(Error.prototype);
websocket error: Cannot read property 'getAO' of null

websocket error: Cannot read property 'getAO' of null
websocket error: Cannot read property 'getAO' of null

**Comment by tarcisiozf** [comment]
fix is under review: https://github.com/bitfinexcom/bfx-hf-server/pull/117
