### ISSUE TITLE
[bug] HF disconnect not handled

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#592]
Debian / Electron bundle 3.17.0 cloned for build on 2021-09-17.
also Ubuntu / Run-in-browser (development mode)

Comes up since about the time of this fix https://github.com/bitfinexcom/bfx-hf-server/pull/117 (probably).

**What**

After some time, UI shows 'HF Disconnected' and funny overlay shows in the Algo Selection pane.

![obrazek](https://user-images.githubusercontent.com/80652610/133954523-a00654e7-e6fe-44fc-8287-343d43ff0cb4.png)

![obrazek](https://user-images.githubusercontent.com/80652610/133954532-a2433363-0ec9-4f69-a1e1-0fd2fa6c8786.png)

**How often**
Every 3-6 hours, seemingly random. 

**Why**
Probably a true connectivity hiccup. The last occurrence happened to 2 physically separated HW installations (different city districts) at exactly the same time [2021-09-20 01:29 UTC], connected with the same ISP. While other instances elsewhere kept running.

![obrazek](https://user-images.githubusercontent.com/80652610/133955342-e7d612c6-44f5-4b71-8c94-7a40b0698aeb.png)

**Recovery**

Restart the electron package.

**Problem**
The BadConnection modal does not come up as expected. Its auto-restart feature is out of reach and thus automatic AO recovery too. 

Both logs files are completely silent, always.

![obrazek](https://user-images.githubusercontent.com/80652610/133955782-db6ecdd1-598d-4f40-8e7c-d3421231ba03.png)

**Suggestion**
+ observe and log HF connectivity 
+ couple the BadConnection modal as appropriate

Thanks for reviewing,
miro

**Comment by pointops** [comment]
**Additional complication**

When trying to close electron app, the DMS/atomic warning [Algo Orders Pause] comes up. 

However, neither of the 4 buttons [ (Cancel) (Don't show again) (OK) and close modal (X) ] work. Clicking on any of them has no response apart from the mouseover style change.

![obrazek](https://user-images.githubusercontent.com/80652610/133956170-63f8b7dc-3e55-4d2b-a750-7049712cf59d.png)

After this, the UI is effectively locked. 

**Resolve**

'killall bfx-hf-ui' from the terminal, or container restart.

**Comment by Blaumaus** [comment]
Thanks for the report, I'll take a look at it

**Comment by pointops** [comment]
btw: what is the location of log-files when running in-browser in DEV mode?

**Comment by pointops** [comment]
> 
> 
> **Additional complication**
> 
> When trying to close electron app, the DMS/atomic warning [Algo Orders Pause] comes up.
> 
> However, neither of the 4 buttons [ (Cancel) (Don't show again) (OK) and close modal (X) ] work. Clicking on any of them has no response apart from the mouseover style change.
> 
> ![obrazek](https://user-images.githubusercontent.com/80652610/133956170-63f8b7dc-3e55-4d2b-a750-7049712cf59d.png)
> 
> After this, the UI is effectively locked.
> 
> **Resolve**
> 
> 'killall bfx-hf-ui' from the terminal, or container restart.

Does not replicate

**Comment by bhoomij** [comment]
fixed in https://github.com/bitfinexcom/bfx-hf-ui-core/pull/107. 
Feel free to reopen if you face this again.
