### ISSUE TITLE
[bug] algos.json persistent AO - leftover

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#593]
Ubuntu / run-in-browser, Chromium
GitHub release 3.17.x cloned 2021-09-17

**What** 
After re-load from localhost:3000 [F5 refresh], the UI shows a modal to reload an old AO. 

![obrazek](https://user-images.githubusercontent.com/80652610/133958128-5695ae30-c95b-4a91-b0ab-6782298b07c7.png)

Choosing to cancel, the removal unfortunately fails.

![obrazek](https://user-images.githubusercontent.com/80652610/133958182-669a6b32-56e0-4402-bf2f-7fe4d684ca67.png)

Indeed, there was no AO running at the moment, the one from the modal was picked from the background (*~/.honeyframework/algos.json*, right?).

**Problem**
The leftover AO record is persistent and comes up with the modal on every future re-load of the HF-UI

**Logs**
+ ds-bitfinex: nothing really, normal reconnect for the refresh

+ api-server:

>   bfx:hf:server:ws-server:api client 1631995626765 disconnected +8s
  bfx:hf:server:ws-server:api client 1631995626766 connected +9s
  bfx:hf:server:ws-server:api identified +443ms
  bfx:hf:server:algo-worker spawning bfx algo host (dms enabled) [aff xZvWHMNR] +2m
  bfx:hf:server:algo-worker spawned host for HF_User +1ms
  bfx:hf:server:ws-server:api opening auth bfx connection (dms enabled) +165ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue open +2m
  bfx:hf:algo:ao-host:ws2:process-message process open +2m
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue auth:success +27ms
  bfx:hf:algo:ao-host:ws2:process-message process auth:success +27ms
  bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:snapshot +6ms
  bfx:hf:algo:ao-host:ws2:process-message process order:snapshot +6ms
**websocket error: Error removing order: bfx-ping_pong [1476272390144]
  bfx:hf:server:ws-server:api error removing order 1476272390144 [bfx-ping_pong]: Error: Response timeout for n:oc_multi-req:1476272390144:success and n:oc_multi-req:1476272390144:error
    at Timeout.<anonymous> (/home/username/bfx-hf-ui/node_modules/bfx-api-node-core/lib/util/watch_response.js:32:14)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) +6s**
  bfx:hf:server:ws-server:api removed selected orders [] +0ms

**Resolve**

![obrazek](https://user-images.githubusercontent.com/80652610/133958987-fc6648c9-4c3a-4200-b350-fbf55acf171b.png)

Manually update *algos.json*, change *active state* to "false"

**Suggestion**
Whenever the server returns a failure / error message of AO handling, flag this AO immediately as 'active : **false**' in *algos.json*.

Thanks for reviewing,
miro

**Comment by avsek477** [comment]
Fixed in HF version 3.18
