### ISSUE TITLE
[bug-unusable] There is no EXECUTE button in the strategy editor.

### ISSUE THREAD

**Issue by drrammstein** [bitfinexcom/bfx-hf-ui#596]
The API connects without errors, both on paper and in production. Backtest runs successfully, but there is no EXECUTE button in the interface. v3.18.0
![Снимок](https://user-images.githubusercontent.com/10552123/134471639-d74bdf69-e135-4637-be58-604c7c7a3d48.PNG)
![Снимок2](https://user-images.githubusercontent.com/10552123/134471635-6722be63-f89c-4ee8-836f-2bd6dd3b62a5.PNG)

**Comment by avsek477** [comment]
This feature will be available in the next HF version. Please stay tuned :)

**Comment by drrammstein** [comment]
Thank you!
