### ISSUE TITLE
(bug) BadConnection modal does not come up

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#599]
Today's build after the last -core merge: https://github.com/bitfinexcom/bfx-hf-ui/commit/8f3f3e66430c5e5096aa9773c37746fdfca7c5ae, but no improvement.

Using "Reboot Automatically on Bad Connection" = *false*

![obrazek](https://user-images.githubusercontent.com/80652610/135666580-81b93ec4-bc1d-4581-ae56-a5036e15dbe5.png)

IIRC the Bad Connection modal was not ever seen after this fix: https://github.com/bitfinexcom/bfx-hf-ui-core/pull/79
- applies both to electron production and in-browser development mode.

Apart from the overlap / graphical mess no longer happening, the functionality has not improved since https://github.com/bitfinexcom/bfx-hf-ui/issues/592.

The nice graphics from https://github.com/bitfinexcom/bfx-hf-ui-core/pull/92 does not show.

Logs are rather silent: 

![obrazek](https://user-images.githubusercontent.com/80652610/135666463-1e149af2-cdc3-4094-896f-1a93b1fd3562.png)

![obrazek](https://user-images.githubusercontent.com/80652610/135666512-6bec92e2-a5c1-4654-a56b-a17132ad3dc9.png)

Algo Entry panel is wiped:

![obrazek](https://user-images.githubusercontent.com/80652610/135666182-1377b4e9-e79a-4fa4-81a4-c33647d256f0.png)

The HF Disconnected (red) shows.

![obrazek](https://user-images.githubusercontent.com/80652610/135666709-a8deb3cc-21d5-4468-aa48-0ddd1b01dd8c.png)

**Comment by bhoomij** [comment]
@pointops could you provide steps if any to repro this ?
what I tried is turning internet off, and get bad connection modal after 30-60 seconds.

**Comment by pointops** [comment]
For me it happens every time there's a indicated disconnect.

I will have look, might take a couple of days.

**Comment by pointops** [comment]
Issues persist in 3.19.0

**Comment by pointops** [comment]
The HF disconnect here is caused by the favourites filter, but left untrapped. Just an example only, HF disconnects are recurring without me being able to track them. 

I assume WS remains live, hence the modal is not triggered.

**capture** https://www.screencast.com/t/tjji3Uj0n timestamp just after 00:56

**Comment by pointops** [comment]
Bad Connection Modal comes up with the lastest release.
