### ISSUE TITLE
Submitting API credentials does not unlock Order Form

### ISSUE THREAD

**Issue by f3rno** [bitfinexcom/bfx-hf-ui#60]
After entering the API Key/Secret on a fresh install, the order form does not redirect from the credential submit form, even though the server successfully connections to Bitfinex.

After a restart it works as expected.

**Comment by JacobPlaster** [comment]
Does this occur on both electron and in the standard browser?

**Comment by f3rno** [comment]
Also happens in the browser; debugging now.
