### ISSUE TITLE
(bug) The Recover AO modal displays "invalid date"

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#610]
'Created' field has some value mismatch.

![obrazek](https://user-images.githubusercontent.com/80652610/137482672-85b1587e-3c34-4215-ab63-bbc6db1ec02e.png)

**Comment by bhoomij** [comment]
@Blaumaus please have look if something is missing related to https://github.com/bitfinexcom/bfx-hf-ui-core/pull/123

**Comment by Blaumaus** [comment]
![Screenshot from 2021-10-18 15-01-42](https://user-images.githubusercontent.com/35810911/137726434-0927d38c-ba6e-4e80-a8ac-20fef62a6ecc.png)
I can't reproduce this issue.

@pointops did you run `npm i` on `bfx-hf-ui`, because this feature depends on the latest changes to `bfx-hf-server`
