### ISSUE TITLE
(bug) Order Book GUI component retains BTC:USD

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#618]
Changing trading pairs doesn't enforce re-load of the order book data. 

 https://www.screencast.com/t/CwD51KIV5UV
 
 The label changes to SUSHI / XMR / etc, however the graph still shows BTC price.
 
 Can be rectified by closing the Order Book element and introducing it again. Other 'soft reset' i.e. changing from Trading Terminal to Market Data does not help.

**Comment by Blaumaus** [comment]
Working on a fix...

**Comment by pointops** [comment]
thanks.

**Comment by pointops** [comment]
Build from Master on 27NOV (development mode): Still occurring.

![obrazek](https://user-images.githubusercontent.com/80652610/143688611-5ba3c11b-edcd-4a73-b676-659eeb7c5a63.png)

**Comment by pointops** [comment]
Seems fixed.
