### ISSUE TITLE
(bug + improve) stored Algo Parameters

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#619]
**bug**

When deleting an unwanted entry, pressing the trashbin icon will load the form. Not desirable, just erase it.

https://www.screencast.com/t/Uvt7qrBkPYd

**improvement request**

1) 
After pressing the trashbin icon, do not close the list-box of stored Algo Parameters. Keep it open to allow more housekeeping.

2) 
In addtion, also store the EXCHANGE v.s. MARGIN choice.

**Comment by Blaumaus** [comment]
Will fix this one
