### ISSUE TITLE
[bug] AO counter not updated after failure

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#705]
The counter of AOs shows the total of all prescriptions, not just the active ones.

![image](https://user-images.githubusercontent.com/80652610/185549476-60d8ffd9-f86f-43f0-aec5-3678b64f5160.png)

The screenshot shows 2 AOs which had failed internally / suffered uncommanded termination and 1 AO still alive.

Suggestion
+ update AO counter from (3) to (1) whenever AO stops
+ provide means of deleting the dead AO entry, such as a trash-bin icon.

![image](https://user-images.githubusercontent.com/80652610/185549127-7f967e03-0b04-48ad-b984-81336a8cd40e.png)

**Comment by pointops** [comment]
*n.b.* automatic removal of the dead AO listing is not desirable. As of now, the EDIT icon can be used to re-animate it which is useful.

**Comment by hugoscm** [comment]
Hi @pointops ! Thanks for the heads up. Just wanted to mention that you can also report bugs, make any suggestion you like and review the current pipeline at https://bitfinex-honey.upvoty.com

**Comment by hugoscm** [comment]
This is in the pipeline

**Comment by hm-bfx** [comment]
This was fixed in yesterday's release 3.30.3

**Comment by pointops** [comment]
Regret to screenshot it is not. :-(
On 02.09.2022 16:30:38, Product @ BFX Honey ***@***.***> wrote:
This was fixed in yesterday's release 3.30.3

**Comment by hm-bfx** [comment]
hmm thanks for the confirmation @pointops so the same image you posted above remains the same? no change to the value (3)?

**Comment by pointops** [comment]
![obrazek](https://user-images.githubusercontent.com/80652610/188103220-d350e071-4336-4448-8456-bc65ddaebc66.png)

Here's what I have, approx 4 hours after starting from scratch on 3.30.3 release.

**Comment by pointops** [comment]
![obrazek](https://user-images.githubusercontent.com/80652610/188103820-d955df55-3356-4eec-8e4c-2186f9f0da4d.png)

**Comment by hm-bfx** [comment]
Thanks @pointops we're on this one

**Comment by tarcisiozf** [comment]
@pointops can you share what type of error messages you get when the AO "failed internally"? logs would be helpful too.

thinks like this error below is getting captured and removed from the list.
![image](https://user-images.githubusercontent.com/8385226/188509919-f56ae1d5-d2f0-41c5-80e5-2e7aaaa1df76.png)

**Comment by pointops** [comment]
Hi Tariciso, that might take a while.

I practically don't get any logical failures (balance / post-only) at all. My AOs simply don't reach the edge case because they are removed **unlogged and unannoucned** well before this could ever happen.

**Comment by pointops** [comment]
No, let's close. 

There is a different behaviour now where handling of failed AOs (probably disconnect induced) may still need some work. Better report that separately? 

Closing this one.
