### ISSUE TITLE
[bug] Data inside Order Book compnent default to BTC:USD pair

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#712]
***3.30.1 stable***

![image](https://user-images.githubusercontent.com/80652610/186789203-729f89a3-cde8-4967-b25b-05300356cd18.png)

Reloading the Trading Terminal UI by switching to Market Data and back used to help, but now it does not.

Switching view to Stacked and back does not fix it either.
![image](https://user-images.githubusercontent.com/80652610/186789618-86568c95-a677-47ce-842c-4258451031ca.png)

Solution is to remove the component altogether and re-introduce it.

Apart from fix at launch, is there a chance of getting a "force refresh" aka "reload" button on top of the component bar? Would be also helpful to restart the Chart element that keeps disconnecting.

**Comment by pointops** [comment]
**3.30.2-rc2** same issue.

suggestion: 

![image](https://user-images.githubusercontent.com/80652610/186790089-812b7831-3f37-4a73-b659-882ddb5f84ec.png)

**Comment by pointops** [comment]
changing the trading pair manually does not help. 

![image](https://user-images.githubusercontent.com/80652610/186790289-b6bf1078-df2e-4779-8a2c-a476cb22c5dd.png)

**Comment by hugoscm** [comment]
In review right now. It should be addressed ASAP. Thanks for the report

**Comment by pointops** [comment]
no problem.

Kindly note it had been reported and closed last year: https://github.com/bitfinexcom/bfx-hf-ui/issues/618

**Comment by hm-bfx** [comment]
Hi @pointops. This was fixed in yesterday's 3.30.3 release with PR https://github.com/bitfinexcom/bfx-hf-ui-core/pull/524

**Comment by pointops** [comment]
Looks good, appreciated.
