### ISSUE TITLE
[improve] Enable selection of trading pair by click on the active position or AO.

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#716]
Present: 

Trading pair label on "POSITONS" only has a mouse-over tag.

![image](https://user-images.githubusercontent.com/80652610/187444722-bd35a29c-13fc-435a-9fd4-f483e413837e.png)

Requested:

Similar to Bitfinex WebGUI for Trading, provide means of changing the trading pair by clicking on the active postion label.

![image](https://user-images.githubusercontent.com/80652610/187445707-f67af675-f2b7-48c6-b4e6-93c3dc5a67d1.png)

(not easy)

Suggested: 

Provide same feature for AO pane, click on the AO will redirect to the relevant trading pair.

**Comment by hm-bfx** [comment]
Thanks! Moved to the[ Discussion Board](https://bitfinex-honey.upvoty.com/b/improvements/convert-trading-pair-label-into-an-active-link/).

Also @pointops , would love your thoughts on this feature suggestion -> [an IDE built to create custom algo orders](https://bitfinex-honey.upvoty.com/b/exploration-/create-custom-algo-orders-with-code). Would this be useful to you?

**Comment by pointops** [comment]
That is well beyond my IT prowess. 

However, this specific request comes from a bucket, that is clearly defined: 
Equip Honey with UI features so that the need for parallel parallel inside HONEY and BFX main WebTrading GUI is eliminated.
