### ISSUE TITLE
[improve] Order History panel to sort by 'last triggered' atomic i.s.o. 'placed'

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#717]
On the Order History panel, for now the entries can be sorted by their 'placed' timestamp.

As AOs have their atomics dynamically generated and filled on logical basis rather than chronological one, 'placed' has very little practical meaning to survey the workings if any at all.

![image](https://user-images.githubusercontent.com/80652610/187572865-5c2dd3af-fc72-4cfd-892d-2f4b988aa3bc.png)

Request (useability boost 600%):

Replace the 'placed' column with 'inactive' a.k.a. 'triggered' a.k.a. 'touched last at' similar as we have on fullsize Bitfinex.com Trading WebGUI.

Note here - Order HISTORY has 'inactive'

![image](https://user-images.githubusercontent.com/80652610/187572829-7e1e5a87-40ce-41a1-a13a-55ad44aad691.png)

and thus is showing the filled orders and atomics - that's what Honey is missing. 

NOTE: The full WebGUI shows PLACED timestamp for orders, true, at the ORDERS panel. This is identical to Honey ATOMICS (Created).

![image](https://user-images.githubusercontent.com/80652610/187573288-fd3f4e6a-652e-40f2-a3cb-bf172a9be164.png)

![image](https://user-images.githubusercontent.com/80652610/187573230-905eb63b-dadd-453e-bf6e-cc07f8b7ee15.png)

**Comment by hm-bfx** [comment]
Great suggestion. Thanks. You can track implementation status [in the discussion board](https://bitfinex-honey.upvoty.com/b/improvements/order-history-panel-sorting/)

**Comment by pointops** [comment]
May I suggest this has been offered already quite some time ago, thus now we have 2 votes on the issue?

https://github.com/bitfinexcom/bfx-hf-ui/issues/611

**Comment by hm-bfx** [comment]
Lots has changed since #611, specially since early 2022, and will do so going forward - hopefully for the better :) 

Part of that, is to centralise the feedback from all sources into the same space in the [discussion board](https://bitfinex-honey.upvoty.com/b/improvements/order-history-panel-sorting/). This will allow us to respond faster, deliver more relevant features and any user to track how their reports and suggestions move in the pipeline. Issues initiated on Github, such as this, will be updated in both places as they are moved forward.

**Comment by pointops** [comment]
Honestly I am not qualified to comment via GitHub anyway... might give it a try. Shame I cannot access upvoty without VPN.

**Comment by hm-bfx** [comment]
Hmm thanks for reporting that VPN access issue, we did not consider issues accessing the board. You can post anonymously if you can access it though, no need for a registered account.

**Comment by pointops** [comment]
Please disregard the comment on Upvoty access, I have edited the comment accordingly. 

Where I am sometimes VPN improves the general accessibility, sometimes it makes it worse. This seem to have been a transient issue.
