### ISSUE TITLE
[improve] README.md new section 'Pre-requisites'

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#718]
With reference to https://github.com/bitfinexcom/bfx-hf-ui/issues/609, which went closed unnoticed.

SUGGESTION:

add a new section 'Pre-Requisites' to README.md, possibly to include: 

> Node.js version 15.x
> npm version 7.x
> node-prune
> make
> gcc
> g++
> zip
> web browser for hosted app (Mozilla XX, Chrome/ium XX, Edge XX)
> 

whichever is actually needed at the moment.

**Comment by pointops** [comment]
The build-css script required to run the electron version in browser developlent mode was already reported missing then (despite lack of understanding what it exactly was missing) and it only appeared 9 months later.

**Comment by hm-bfx** [comment]
We're moving and updating all documentation to a new platform. We will be taking this into consideration.

**Comment by pointops** [comment]
> We're moving and updating all documentation to a new platform. We will be taking this into consideration.

The source repository will remain on GitHub, I suppose, and large part of the qualified users will still compile by themselves.

Having a more clear message how to setup the system for running BFX Honey over here remains very appropriate.

**Comment by ivanori1** [comment]
@hm-bfx  can this task be closed ?

**Comment by hm-bfx** [comment]
@ivanori1 the issue raised in this topic is addressed but when the full docs go online I'll raise that here. I'd prefer if it was @pointops closing it, which means the concerns have been addressed.

Nevertheless @pointops, although I understand your comment, we have so many public repos that maintaining accurate and updated documentation across all would prove impossible at this stage. We will move to centralise the documentation. Each project readme will show the link where users (including those running from source) can find the full info (including - hopefully - the one you requested) to the adequate level of quality and clarity

**Comment by pointops** [comment]
Understood. Obviously this suggestion applies for this project specifically and indeed would miss large parts of the big picture.

Kind regards, p/o.
