### ISSUE TITLE
[feature] Monitoring AO count via API

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#723]
Support request to underpin the larger task of order longevity with **API retrieval of active AO count**.

_Survival time of simple Ping-Pong recurring AO is about 12 hours if not active with hits and around 5 hours if the orders actually get triggered. Observed behaviour is quite the same over the last 10 months, August 2021 was the peak reliability period of up to 3 days with orders clicking away but that magic was lost and never seen again._

PROBLEM:
Loss of AO at BFX Honey cannot be tracked. Independent of the reason behind, successful closure, logical failure, connectivity reset, or uncommanded flush.

SUGGESTION:
Develop API WS2 to include the number of valid running AOs. 

https://docs.bitfinex.com/reference/ws-auth-orders

NOTE: 
If Bitfinex servers actually load-balance by killing AOs (can be justified, hard to tell without any log trace https://github.com/bitfinexcom/bfx-hf-ui/issues/722) this becomes even more important. Working with a tool limited this way is fine as long as the situation is reported to the user in a controlled manner. 

For other cases of AO termination, monitoring via API is equally relevant. Algorithmic trading is less than half-success if it cannot be automated to a reasonable extent - not knowing the AOs have closed uncommanded falls markedly short of target.

WARN:
Pending the resolution for BFX honey to actually report the active AO count correctly. Issue: https://github.com/bitfinexcom/bfx-hf-ui/issues/705

**Comment by pointops** [comment]
One of the key improvement features, withering.

**Comment by pointops** [comment]
Still a key feature sought.

**Comment by hm-bfx** [comment]
Logging has been totally overhauled. Might be released on the next latest 3.31.3. The following actions will be logged for every AO: `ao_init`, `ao_updated`, `ao_cancelled`, `ao_failed`. Hopefully this fulfills the requirements.

**Comment by pointops** [comment]
Great news. Will try and report back 8-)

**Comment by pointops** [comment]
The core feature here was pulling the AO active order count via WS2 API from Bitfinex. 

As of now, inside Honey, we don't seem to have that number as a live variable. The Trading State panel indicator siphons off the Algo.Orders modal (with small labor pains such as displaying the historical orders when that selector is depressed https://github.com/bitfinexcom/bfx-hf-ui/issues/786)

**Comment by pointops** [comment]
Still requested.
