### ISSUE TITLE
[bug] AO wipe at API-server re-connect (untrapped)

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#726]
Caught on tape, twice and slightly different.
(use full-screen view of the stream video to target the location more easily)

timestamp 10:11:35 onwards
https://www.screencast.com/t/XxSPqqNh

timestamp 4:48:48 shows a some sort of re-sync which results in a kill of the AO.
Different from the screencast above, this case has the HF-reconnect at 04:47:10 indicated with GUI lables and the AO survives that. Only a bit later a separate API-server reload wipes them out in complete silence.
https://www.screencast.com/t/QkLzHeMAUIe

fix:
not sure, the reason for the reconnect not understood. If due arbitrary refresh from BFX server, why cancel the AOs and not keep them?

improvement:
+ log the cancellation of orders anytime this happens

suggestion : 
+ display the modal 'connectivity issue: restart'
+ restart the app 
+ display the 'AO reload' modal.

**Comment by pointops** [comment]
Edited the report above for clarity.

**Comment by pointops** [comment]
Behaviour unchanged so far.

**Comment by pointops** [comment]
Confirmed on 31.2

**Comment by hm-bfx** [comment]
This seems addressed on https://github.com/bitfinexcom/bfx-hf-ui/issues/782 - that issue is currently under review

**Comment by pointops** [comment]
Possibly, it's a long-standing issue. For the moment the 'meta-reload' events are still a thing. No definite pattern was found, although mostly they happen in bursts and affect mulitple geo-dis-located instances around the same time.

**Comment by pm-bfx** [comment]
Given the new changes in 3.31.4 could I suggest we close this one and merge it with https://github.com/bitfinexcom/bfx-hf-ui/issues/813?

**Comment by pointops** [comment]
Agreed. With the recent build, the cancellations are logged better and trapped, no longer it is just a silent disappearance.
