### ISSUE TITLE
[improve] Client disconnects from HF not logged

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#727]
Reporting separately from other issues, since the last capture shows them happening in sequence and independently.

OBSERVATION:
A temporary disconnect from HF is indicated by the green indicator blinking red and correct sequence of GUI flags (bottom right corner). However nothing is logged in the process watch window. 

SUGGESTION:
Provide logging of HF disconnects for error tracing and mitigation.

SCREEN:
timestamp 4:47:10 (use fullscreen view for easier targeting)
https://www.screencast.com/t/QkLzHeMAUIe 

NOTE: 
The AO actually survives this HF hiccup at 4:47:10, which is nice.

**Comment by hm-bfx** [comment]
Added to the pipeline. Thanks
