### ISSUE TITLE
[bug] AO reload denied due self-inflicted MAX ORDER COUNT 

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#728]
**30.30.3 stable** long running glitch

CASE: 
BFX Honey is restarted / reloads for any reason (most common is connectivity drop) and the recently running AOs are offered for quick recovery. 

The orphaned atomics need to be cleared out first before being re-introduced by their parent AO.

PROBLEM:
**sometimes** the cancellation of old atomics is not fast enough and an AO being reloaded fails to activate due to MAX AO COUNT conflict (100 pcs per trading pair). 

SUGGESTION:
Introduce (or increase) a delay 1000 ms after clearing out leftover atomics and before re-launching the AOs to prevent MAX AO COUNT collision when loading the new set.

CAPTURE: 
https://user-images.githubusercontent.com/80652610/188303370-ca088ab9-6a9e-4c1c-9c1a-d7206b20f113.mp4

**Comment by hm-bfx** [comment]
As usual your contribution is much appreciated! This is under review, I [added the issue to the board](https://bitfinex-honey.upvoty.com/b/improvements/ensure-all-atomic-orders-are-cleaned-before-relaunching-aos-to-prevent-max-ao-count/) so you could follow the evolution
