### ISSUE TITLE
[bug] GUI cross 'X' for manual AO termination goes missing

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#737]
**3.30.x**

On the ALGO ORDERS panel, the 'X' icon goes missing when user view is switched from 'Trading Terminal' to 'Market View' and back.

See video timestamp 1:45 onwards.

https://user-images.githubusercontent.com/80652610/190921906-24ede26e-4d5d-4df4-a634-5b5d12b4acb7.mp4

The beginning of the capture shows:
i) launch of new instance after fresh compile (~/.bitfinexhoney/ui.json preserved manually)
ii) cancelling the atomics manually at BFX main trading web GUI.
iii) starting 2 new AOs from the saved templates
and then the issue being reported.

PROBLEM:
Until recently the (non)display of the crosses could be used to determine whether an AO is running or collapsed. 

They are for sure running in the screen capture, but the missing cross is confusing.

The capture follows with this: 

https://user-images.githubusercontent.com/80652610/190922142-506fe358-7fe9-42b5-be41-c18d2f8dfbe6.mp4

An attempt to close session properly identifies the AOs and they get shut down. The session does not terminate, however I am not sure if this is not a limitation of the development mode (?)

**Comment by ivanori1** [comment]
Thanks for reporting, is fixed and will be visible on tomorrows release 

https://user-images.githubusercontent.com/22149270/191437640-13a5d958-23e9-471b-a624-cf17d2029e52.mov

**Comment by pointops** [comment]
Thank you, already working on my side too.
