### ISSUE TITLE
[bug] Error after submitting API keys (non-stable 3.31.0)

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#741]
Pulled [3.31.0 ?] from GitHub just now [04:05 UTC] , this appears after submitting the API keys.

![image](https://user-images.githubusercontent.com/80652610/191890993-96c147b6-fea8-4a60-a85d-309c4111d45f.png)

**Comment by tarcisiozf** [comment]
Hey @pointops, thanks for reporting. This is now fixed, and it will be included in the final version of 3.31. 

Please be aware that the release-candidate versions (tagged with `-rc`) can be more unstable and unpolished, so I don't recommend using those for actual trading.
