### ISSUE TITLE
[bug] Electron build: Accessing logs and their folder fails

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#762]
i)

![image](https://user-images.githubusercontent.com/80652610/202008719-f9561875-f83b-4aa9-9461-a45ea18ebe50.png)

ii) click 'Open Logs Folder'

iii)  
![image](https://user-images.githubusercontent.com/80652610/202008760-dbd53c3e-55cb-4c5e-a4bb-d4dc3785018d.png)

to 'Open Data Server Log' 
or 'Open API Server Log' 

the result is similar.

**Comment by pointops** [comment]
Persists on 3.31.2 STABLE.

**Comment by dmytroshch** [comment]
@pointops hello. which distribute kit of linux are you using? I can't reproduce it on Ubuntu 22/20

**Comment by dmytroshch** [comment]
also this [issue](https://github.com/bitfinexcom/bfx-hf-ui/issues/779)

**Comment by pm-bfx** [comment]
hi @pointops we can't reproduce this issue . Tried in multiple different linux envs with electron. Hope you can try again on the next release 3.31.4

**Comment by pointops** [comment]
I may have a look at the Electron builds again approx 1st week of April.
