### ISSUE TITLE
[bug] Electron build: Reboot on disconnect misbehaves

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#763]
Once the App detects a connectivity problem and request a reboot, 

![image](https://user-images.githubusercontent.com/80652610/202287515-de875f07-a87c-400b-8203-b39c3ce66953.png)

instead of re-booting it actually attmepts a re-set - asks for a new password, etc...

![image](https://user-images.githubusercontent.com/80652610/202253354-d72d327b-1f44-4ee3-ac02-7ed115928418.png)

Workaround: 

Restart it all manually instead by
+ closing the app window / terminating the process
+ launching again
= normal start with prompt for password, afterwards all is as expected on the inside.

Suggestion: 

During advertised re-boot of the App assure identical behaviour to normal close / run.

**Comment by Tetita** [comment]
Esta manipulando mi teléfono en absoluto no deja que ingresé me cuesta mucho pero lo estoy logrando poco a poco

**Comment by Tetita** [comment]
![Screenshot_20230115_210347](https://user-images.githubusercontent.com/89341644/212590121-3cf94edc-8e3f-4921-ba1a-bdb176173a46.jpg)

**Comment by Tetita** [comment]
![202287515-de875f07-a87c-400b-8203-b39c3ce66953](https://user-images.githubusercontent.com/89341644/212590300-bc63db4f-39e9-4a16-aec4-4fc7cfd17105.png)

No tengo internet
