### ISSUE TITLE
[bug]Order wipe at lost connectivity does not work

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#768]
Electron bundle, latest.

During a connectivity problem a modal comes up informing the user the AOs have been stopped and atomics wiped.

Not true, the atomics are still standing.

![image](https://user-images.githubusercontent.com/80652610/203253019-fffe8d3b-5c1f-4aa6-b14d-89a02adab769.png)

Even after pressing the Reboot button.

**Comment by hm-bfx** [comment]
This issue is being reviewed again after https://github.com/bitfinexcom/bfx-hf-ui/issues/782

**Comment by pointops** [comment]
Appreciate the feedback!

M.
On 28.01.2023 14:38:16, Product @ BFX Honey ***@***.***> wrote:
This issue is being reviewed again after #782 [https://github.com/bitfinexcom/bfx-hf-ui/issues/782]

**Comment by pointops** [comment]
The original report is not accurate.

 Modal says "AOs and strategies" "cancelled" which I misperceived as "strategies, AOs and their atomics wiped". 
 
 Suggested re-phrase:
 Strategies and AOs have been stopped due to a connection issue, atomics may have been retained. 
 The DMS wipe of all Honey orders is configured with [DMS_delay].
 
 The above attempts to separate the terminology of 'orders' (general) from AOs (algorithms) and Atomics (individual, single-point). As well subtle explanations that DMS will not affects orders entered outside Honew (main web UI, right?)
