### ISSUE TITLE
[bug] Auto-update 3.31.1 -> 3.31.2 fails (electron AppImage)

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#779]
An impressive feature, BTW.

screenshot: 

![image](https://user-images.githubusercontent.com/80652610/207991384-92393b45-cc23-45a9-9f85-ea1e4ea0470c.png)

At first the 'temp-' seems to be the problem but indeed the dir is emtpy.

Only reporting the result, did not check the updater code.

mXm
p/o.

**Comment by hm-bfx** [comment]
Thanks for the find. Could you confirm if your previous/current install was from .AppImage or the .zip? 

.zip installs don't support the auto-update functionality (nevertheless, it also shouldn't have been triggered)

**Comment by pointops** [comment]
That's an AppImage station, the file placed at ~/Apps/.

**Comment by pointops** [comment]
Cannot comment a.t.m, stopped using the Electron for a couple of reasons. 

This was not one of them, BTW.
