### ISSUE TITLE
[bug] Re-sync with 'meta reloaded' removes AOs (master)

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#782]
Follows on https://github.com/bitfinexcom/bfx-hf-ui/issues/757

**Comment by pointops** [comment]
3.31.2 

The re-connect comes with very little logging but is easily trackable with the 'meta reloaded' event. On the occasion, 
- a stable pattern is logged from the api-server
- all AOs get flushed, their atomics remain
- UI shows both HF and WS red momentarily
- UI shows re-connect notification. however, nothing is logged on the ws-service

Video showing the AO list, notification area, and terminal window:

https://user-images.githubusercontent.com/80652610/208992919-765747a4-0de1-4010-8358-8f1116bd08fb.mp4

**Comment by pointops** [comment]
A different case caught on tape a few hours later. 

notification tray:

**Comment by pointops** [comment]
However, the issue seems independent of any errors. Multiple meta reloaded events are re-occurring without any errors at all. 

![obrazek](https://user-images.githubusercontent.com/80652610/208997448-a7b18854-84a1-43b9-ba2e-6397b13d2568.png)

(different station, btw)

**Comment by pointops** [comment]
Another angle on the screen, to record the GUI response. What's captured happened spontaneously, without any user interaction.

https://user-images.githubusercontent.com/80652610/209391830-9e742d1c-daf8-4f45-9e5a-680de0900a6d.mp4

**Comment by hm-bfx** [comment]
We're looking into the AOs being killed and how best to handle it.

Regarding the orphaned atomics part of the ticket, we've ran some tests and the DMS seems to be working correctly on the electron build - after 1min the orphaned atomics are automatically killed. You've mentioned before that you're using a different setup, but dev env should work the same... is the DMS setting enabled? (we're aware of issue #731 waiting for the new logging feature since it seems to be a logging issue)

**Comment by pointops** [comment]
Hi. This #782 does not complain about the orphaned atomics specifically, it seems, but hopefully I catch the question. 

The 1 minute explanation does it for me, not a bug but a feature. If there was a selection for the delay in settings, this could be self-explanatory to an observant user. 

If you mean #768 - that was about incoherent GUI: saying the orders are cleared but they aren't. But I see my mistake in reporting/understanding now and will comment over there.

Sorry for the headbang. ;-(

**Comment by pm-bfx** [comment]
Given the new changes in 3.31.4 could I suggest we close this one and merge it with https://github.com/bitfinexcom/bfx-hf-ui/issues/813?

**Comment by pointops** [comment]
Merge is acceptable, sure. Though I see 2 distinct issues:
a) meta reload event (#813) happening
b) Honey dropping the AOs (this one)

Agreed, the 'auto-resume' works well to recover. Thus both these become inside engineering issues without directly affecting the user. Most importantly, the wipes are now displayed to the user.
