### ISSUE TITLE
bfx-hf-tradingview is not opensource?

### ISSUE THREAD

**Issue by duylddev** [bitfinexcom/bfx-hf-ui#783]
Honey Framework is using bfx-hf-tradingview to display chart, but it is not an open source and it calls to localhost to get strategy and candle data.

Any chance I can use bfx-hf-tradingview to access from internet (not localhost)?
is bfx-hf-chart ready for production?

**Comment by dmytroshch** [comment]
Hello. TradingView is deployed on https://bitfinexcom.github.io/bfx-hf-tradingview/

**Comment by dmytroshch** [comment]
check an example of usage that component
https://github.com/bitfinexcom/bfx-hf-ui-core/blob/main/src/components/Chart/Chart.js

**Comment by duylddev** [comment]
> Hello. TradingView is deployed on https://bitfinexcom.github.io/bfx-hf-tradingview/

I see, but it's a black-box that I don't know what is inside.
Could you send me those code without tradingview code inside, just the way how Honey Framework connect to Tradingview chart

Thanks

**Comment by Blaumaus** [comment]
@duylddev, the https://bitfinexcom.github.io/bfx-hf-tradingview/ accepts several GET parameters:
 - `env` - the environment. It can be either `electron` (you'll need to have bfx-hf-ui running locally for that to work as it'll connect to localhost to grab the data) or `production` (connects to Bitfinex production servers).
 - `locale` - en | ru | es | tr | zh | zh_TW | pt (i.e. the locales Bitfinex Honey supports itself).
 - `theme` - honeyframework-theme:dark-mode | default-theme:light-mode (the themes Bitfinex Honey supports itself).
 - `iframeID` - that's the tricky one as it's used to differentiate the charts displayed on one page. Basically it's the chart identifier. You need this to supply the currency data to the chart instance.

To communicate with the chart you'll need to use [post message API](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage), see the examples of how the Bitfinex Honey [here](https://github.com/bitfinexcom/bfx-hf-ui-core/blob/main/src/components/Chart/helpers.js#L4) and [here](https://github.com/bitfinexcom/bfx-hf-ui-core/blob/main/src/components/Chart/useChartIframe.js#L60).
We use post messages to also pass the data about positions, orders, etc.


**What you probably need is simply to make the chart working based on the market parameters.** You can do it as well, here's an example:
https://bitfinexcom.github.io/bfx-hf-tradingview/?base=TESTBTC&quote=TESTUSD&wsID=tTESTBTC:TESTUSD

where:
 - `base` is the base currency
 - `quote` is the second currency
 - and `wsID` is the concatenated string identifier that represents the base / quote pair (see [this](https://docs.bitfinex.com/docs/ws-general#supported-pairs) for more details).

**Comment by hm-bfx** [comment]
@duylddev if you feel your doubts are answered please close the issue when possible. Thanks

**Comment by duylddev** [comment]
Thanks @Blaumaus for very detailed answer.

This PR is closed. Hope you guys keep doing this, I love Honey Framework
