### ISSUE TITLE
[improve] Trading State Panel shows count of all historical orders (when selected)

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#786]
That. 

![image](https://user-images.githubusercontent.com/80652610/215717302-2910a1ab-ec52-425a-8b72-7e7972192ecb.png)

![image](https://user-images.githubusercontent.com/80652610/215717444-8ee53e4e-88b0-4861-b7d3-5994d41fe2f7.png)

**Comment by pm-bfx** [comment]
added to the pipeline. History will deselect on click-out anywhere on the app and the number shouldn't show on the title to not generate confusion
