### ISSUE TITLE
[request] Keep direct view of AO parameters (Algo.Orders panel)

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#788]
Pretty please, much sugar on top, 

it is essential the AO parameters remain in direct view without user interaction. 

Same as now.

![image](https://user-images.githubusercontent.com/80652610/215720503-67637789-765f-4596-8e97-1e902af9eab1.png)

Recently the advanced AO view was available in a mid-build (gone now) and the display was not acceptable at all. 

- Requires interaction (click) to see what the AO was about
- Overlaps the other AO so unable to compare the parameters against others in plain view 
==>> no deal. At all.

**Comment by pm-bfx** [comment]
The rationale behind that was the following:

- the introduction of an alias allows users to be explicit about the order they launch, allowing for immediate identification at a glance (using shorter strings even)
- if the user doesn't provide an alias, the alias is == details (string), so the details show on tooltip

Does this not work at all for your use case? If so maybe we could introduce the possibility for the user to select which columns it wants to see

![image](https://user-images.githubusercontent.com/98524406/221544674-ae24cc34-2d7d-4317-b7ad-933eac43d6cd.png)

**Comment by pointops** [comment]
I will post more feedback later, less critical. As simple adjustment of the default columns width would do neatly. N.B. comparing your (new) and my (old) snippet the directly visible field reduced to 15 characters from about 60. 

The alias feature makes sense. Later maybe we could consider parsing its string to the "save" Algo Param Settings window. 
![image](https://user-images.githubusercontent.com/80652610/221653455-0b93b71c-c255-40c9-8855-3cbba1663e22.png)
</spin-off>


The tool-tip view does not allow for direct comparison among different orders. If we manage to increase the directly visible width, it will be survivable. 

To illustrate a point raised elsewhere: https://github.com/bitfinexcom/bfx-hf-ui/issues/789, using your own snippet...
![image](https://user-images.githubusercontent.com/80652610/221654339-5006a7f3-7e6a-40a0-b1a6-ff8dfdc48466.png)
this space could be reclaimed to enable a wider column of the AO baseline description.

**Comment by pointops** [comment]
![image](https://user-images.githubusercontent.com/80652610/221657732-771290c7-70d2-4408-a46d-f05ad869a3c8.png)

**Comment by pm-bfx** [comment]
It's a fair feedback. Note taken, we'll go back to the drawing board and take this into account. Maybe 3.31.5 (tentative early to mid april)
