### ISSUE TITLE
[improve] Screen real estate - truncate superfluous data fields

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#789]
More information is good, the screen populated with empty data is not.

Some of the values on display could benefit from visual-space optimization (size trim).

![image](https://user-images.githubusercontent.com/80652610/215721725-2b079bf1-6523-499c-9cf4-1773a876b3fd.png)

exch <<= EXCHANGE
mrgn <<= MARGIN 
fund <<= FUNDING  
derv <<= DERIVATIVES

01-30 7:35:08 <<= 1/30/2023, 7:35:08 (no need to display the year, sorting - yes, display - no)
Seriously. https://www.reddit.com/r/funny/comments/4jtat7/comprehensive_map_of_all_countries_that_use_the/

canc <<= CANCELED (hey, there even is a mouse-over tooltip)

![image](https://user-images.githubusercontent.com/80652610/215724075-dbd456b3-574d-4f36-8f9e-914150e24724.png)
the leading zero for hrs is also unnecessary                                                          ^^^                 ^^^^^

**Comment by pm-bfx** [comment]
It's in the pipeline to allow datetime personalization. No ETA for release though.

Note taken on improving status displays and other information. Thanks

**Comment by pointops** [comment]
no functional changes so far.
