### ISSUE TITLE
[bug] 'SELL' radio button creates a BUY order

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#794]
cloned and built 2023-02-09-08:4x

![image](https://user-images.githubusercontent.com/80652610/217764821-b9ae9f77-a0da-4b2e-bd89-550284e1f401.png)

![image](https://user-images.githubusercontent.com/80652610/217764875-7cbcd6d9-a71d-4832-b6cf-6d8eba318155.png)

**Comment by pointops** [comment]
![image](https://user-images.githubusercontent.com/80652610/217990919-32b5a0d3-084f-44f4-9a2e-312decaf7aff.png)

**Comment by pointops** [comment]
Requesting fix. 

For Ping-Ping orders, the SELL button is broken and Honey will create a buy order instead. 

Those are immediately executed. 

Very ugly.

**Comment by dmytroshch** [comment]
We are working on it

**Comment by pm-bfx** [comment]
It's an RC instabiity. Should not be present on the next latest release 3.31.4 (March, 8/9)

**Comment by pointops** [comment]
No issues on 3.31.3.
