### ISSUE TITLE
[bug] 3.31.3-rc.2 unable to setup AO (p-p)

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#799]
(all development mode, no electron)

Fresh clone from GitHub, just after the release of rc.2

Unable to set up a single ping-pong order.

result: 

![image](https://user-images.githubusercontent.com/80652610/220445335-e1cca422-2c82-4cf2-ada3-bffd65202aa0.png)

the attempt: 

![image](https://user-images.githubusercontent.com/80652610/220445426-38dbd261-1a16-4f0d-ade1-cf006a75d9c5.png)

**Comment by pointops** [comment]
![image](https://user-images.githubusercontent.com/80652610/220446045-c1d66f36-d659-4c13-af34-d7368d772499.png)

**Comment by dmytroshch** [comment]
@pointops hello. We are having a broken release candidate due to environment issues. Please wait for the official release

**Comment by pm-bfx** [comment]
Next release will be 3.31.4 on the 8/Mar

**Comment by pointops** [comment]
No issues on 3.31.3 stable
