### ISSUE TITLE
[improve] button labels for AO Edit modal

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#805]
Confusing:

![image](https://user-images.githubusercontent.com/80652610/221247139-a0e2c696-e922-4152-833f-d34278079947.png)

suggestion, please use

>  'Discard' i.s.o. _Cancel_
>  'Re-launch' i.s.o. _Okay_

E.g. if [Okay] is pressed without making any changes, the AO resets. [Cancel] smells like killing the AO, which it does not (major good)

**Comment by hm-bfx** [comment]
Added to the pipeline.

- Change the text of "Okay" button to "Save and Restart"
- Remove "Cancel" button and replace with:
    - keep only "X" button on top-right of the modal
    - if there are changes inform the user that changes will be lost

**Comment by pointops** [comment]
That is a very wholesome design choice, love it!

**Comment by pm-bfx** [comment]
@pointops this change has been implemented

**Comment by pointops** [comment]
Great.
