### ISSUE TITLE
[request] Resizing the application

### ISSUE THREAD

**Issue by 2011** [bitfinexcom/bfx-hf-ui#807]
I have an ordinary 1920 x 1080 monitor - that I run in portrait mode (1080 x 1920). Even after changing the layout of the tiles in the application, I can't make the window narrow enough so that it all fits on my screen. This results in a lot of dragging the application from left to right and back again just to do mundane tasks such as minimization. Can you allow resizing the app down to 1080 pixels wide (perhaps some of the information at the top and bottom might have to take up two lines, but I have plenty of screen real estate in that direction :) )?

**Comment by ivanori1** [comment]
could you send here print screen to see how it looks on exactly in your case ?

**Comment by 2011** [comment]
> could you send here print screen to see how it looks on exactly in your case ?

No problem. I have mostly the default layout here, and I have made the bfx-hf-ui application as narrow as possible.

![left](https://user-images.githubusercontent.com/550150/222316311-076bb571-c1b4-4653-9d54-4ecaeb7ddf9a.png)

![right](https://user-images.githubusercontent.com/550150/222316337-34010637-e5ca-4aa7-b1ea-7aef58506d60.png)

**Comment by dmytroshch** [comment]
@2011 your suggestion will be included in an upcoming release (3.31.4)

**Comment by 2011** [comment]
Thank you.

**Comment by ivanori1** [comment]
are you suggesting zoom out like browsers have CTRL + or CTRL - ? or you are just suggesting to try to fit current app into 1080px, without making size of icons and font smaller? this is fix for the next version and it will contain horizontal  scroll when screen smaller then 1200px 
![Screenshot 2023-03-07 at 2 39 59 PM (2)](https://user-images.githubusercontent.com/22149270/223439215-5792b18a-7e07-4ea2-9631-1896bece7a27.png)

**Comment by 2011** [comment]
> are you suggesting zoom out like browsers have CTRL + or CTRL - ? or you are just suggesting to try to fit current app into 1080px, without making size of icons and font smaller?

I hadn't thought of zooming in and out (althought that would work, as well). I believe that the best solution would allow the user to make the program window narrower, and (if the user altered the layout by stacking the individual components in a more vertical manner) reflow the header and footer to remove the need for a horizontal scroll bar.

**Comment by pm-bfx** [comment]
@2011 let us know your thoughts after the latest `3.31.4` release
