### ISSUE TITLE
[improvement] TradingView panel truncates the display of price too aggresively

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#809]
Illustrated here on XRP/BTC, which may be the edge-most case:

**Honey**

![image](https://user-images.githubusercontent.com/80652610/222191631-f16abca0-df8c-4eaf-be9c-ed90973dd9db.png)

**Main BFX Web GUI**

![image](https://user-images.githubusercontent.com/80652610/222191757-be8fbcbf-2c41-488f-b027-ea2760add96b.png)

**Comment by pm-bfx** [comment]
@pointops does the above proposed solution works for your use case?
