### ISSUE TITLE
[bug] Trading State panel - upon the first load, POSITIONS are not displatyed

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#812]
Development mode, Chromium on Debian@Linode

When re-loading the app (by force-refreshing the browser tab) or on its first launch, the POSITION table is not populated in the Trading State panel

![image](https://user-images.githubusercontent.com/80652610/222410441-09bb9564-b00b-48dc-a230-b8c511ce7137.png)

Workaround, recycle to ATOMICS or ALGOS and back to POSITIONS

![image](https://user-images.githubusercontent.com/80652610/222410565-dbf86c96-f4e2-4f85-a67a-4f3494cd1feb.png)

**Comment by ivanori1** [comment]
I can reproduce this in 1 of 10 tries, not sure what is exact reason of this bug.. but reported and will be in the list, thanks for reporting
