### ISSUE TITLE
[improve] Disconnects with 'meta reloaded' event

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#813]
Honey is handling these quite well after rolling out the latest adjustments. This is major good news, really.

What about the root cause behind them? They seem to be happening in bursts. Sometimes 2-3 days without one, and then a string of them barely minutes apart.

![image](https://user-images.githubusercontent.com/80652610/222624242-6eab3c46-b018-4907-9353-48d61e138d3a.png)

(note: FEB was 28 days only, but there are quiet days now and then. Usually over the weekend)

**Comment by pm-bfx** [comment]
Hi @pointops let's review again after 3.31.4 mid this week. We don't exactly know why meta-reload is triggered tbh, since it's a passive response to a loss of conectivity. Why that connectivity is lost to begin with, or which form it takes, I guess will depend on each user's setup and a myriad of other factors

**Comment by pm-bfx** [comment]
The possibility to dilate the default disconnection time (as mentioned [here](https://bitfinex-honey.upvoty.com/b/improvements/override-the-default-disconnection-timer-control/)) will hopefully be available after `3.31.5 `- this hopefully will help reduce the number of times `meta:reload` gets triggered according to local conditions. 

Nevertheless, for 3.31.4 meta:reload already triggers the AO reset, with the extra setting of the user [now being able to restore all previously running AOs automatically](https://bitfinex-honey.upvoty.com/f/changelog/bypass-the-restart-aos-modal/) - bypassing the behaviour entirely. This can provide a more seamless experience, but it's also more risky.

**Comment by pointops** [comment]
Good news. ;-)
