### ISSUE TITLE
[improve] pressing Enter on keyboard launches an AO (undesirable

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#814]

**Comment by pointops** [comment]
UX volatility, observed after the ALIAS field has been introduced.'

When typing the descriptions in, the user might hit the ENTER key due to personal habits / previous other workflows unexpectedly. In the EXECUTE ORDER pane, this will launch the order unintentionally. While the numerical setup is still in progress

![image](https://user-images.githubusercontent.com/80652610/222627849-a9a4b534-a7a6-4c88-a366-7cf108e1169c.png)

![image](https://user-images.githubusercontent.com/80652610/222627937-59a12a60-6dba-4af0-a72d-23a2c960071b.png)

Come to think of it, this may be the true reason behind some 'spontaneous' AO triggers which had been observed before (never reported, unable to reproduce).

**suggestion**

De-activate the default ENTER key function on all panels / modals _unless_ there is a clear indication to the user that a certain button has become hot. 

Since we do not have that mouse over / focus showing over the individual elements (not really needed) better just to deactivate the ENTER. Optimizing GUI for keyboard control would require that and Honey will still do great for a long time even without it.

**Comment by pm-bfx** [comment]
added to the pipeline. will be disabled until a fully functional key-mapping feature exists
