### ISSUE TITLE
[bug ux] The stalled AO recovery modal disappears with a simple click

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-ui#823]
3.31.4 stable

Once the Non-Active Orders modal is displayed due to Honey re-connect, if the user clicks anywhere outside the panel itself it closes.

https://user-images.githubusercontent.com/80652610/223894453-f5f8d8ae-a068-428b-b8fd-aeca214cc26f.mp4

As a consequence, the opportunity to relaunch the AO is lost completely. The modal won't come back even after a reload of the application.

**suggestion**

a) only close the modal with the [x] button
b) do not deselect the [history] by any-click either
c) allow 'editing' historical orders (copy their parameters to create a new AO) - revive.

**Comment by pm-bfx** [comment]
Hi @pointops ,

agreed on a)

regarding b) you mean that the checkboxes before the orders can only change status if the user explicitly clicks on them? if so agreed.

regarding c) I'm sorry could you elaborate? you mean adding the possibility to edit - in situ - the AOs that were recovered before submitting the modal?

**Comment by pointops** [comment]
Sorry for the delay. 

For b) and c) I had slightly different in mind.

B: kindly see #825. What you suggest in the comment above would be a retrograde step for me (if I understood correctly).

C: kindly see #826.
